export type Role = 'miner' | 'wolf';
export type Direction = 'U' | 'R' | 'D' | 'L';
export type PathKind = 'h'|'v'|'ne'|'nw'|'se'|'sw'|'tUp'|'tDown'|'tLeft'|'tRight'|'cross'|'collapse';
export type ActionKind = 'delete'|'rotate'|'shield'|'scout';
export type SpecialKind = 'block'|'revive'|'swap';
export type Card = { id:string; type:'path'|'action'; kind:PathKind|ActionKind; label:string; rotation:number };
export type Cell = { card:Card; owner:string; shield?:boolean } | null;
export type SpecialUses = Record<SpecialKind, boolean>;
export type Player = { id:string; name:string; role:Role; isBot:boolean; avatar:string; hand:Card[]; score:number; blockedTurns:number; specialUsed:SpecialUses };
export type MapSide = 'left'|'right'|'top'|'bottom';
export type ExternalPoint = { side:MapSide; row?:number; col?:number };
export type ObjectivePoint = ExternalPoint & { id:string; label:string };
export type MapConfig = { id:string; name:string; theme:'mine'|'ocean'|'tomb'; rows:number; cols:number; entrance:ExternalPoint; objectives:ObjectivePoint[]; cardSet:string; obstacleCount:number; obstacleMinCol:number; obstacleMaxCol:number };
export type Treasure = { id:string; revealed:boolean; isGold:boolean; peekedBy:string[] };
export type GameState = { map:MapConfig; board:Cell[][]; obstacles:string[]; players:Player[]; treasures:Treasure[]; deck:Card[]; discardPile:Card[]; turn:number; logs:string[]; winner:null|'miners'|'wolves'; turns:number };

export const GOLD_MINE_MAP:MapConfig={
 id:'gold-mine',name:'Mỏ Vàng Bị Lãng Quên',theme:'mine',rows:5,cols:12,
 entrance:{side:'left',row:2},
 objectives:[
  {id:'top',side:'right',row:0,label:'Rương phía trên'},
  {id:'middle',side:'right',row:2,label:'Rương chính giữa'},
  {id:'bottom',side:'right',row:4,label:'Rương phía dưới'}
 ],cardSet:'mine-basic',obstacleCount:3,obstacleMinCol:2,obstacleMaxCol:9
};

const uid=()=>Math.random().toString(36).slice(2,10);
const defs:Record<PathKind|ActionKind,{label:string;type:'path'|'action'}>={
 h:{label:'Đường ngang',type:'path'},v:{label:'Đường dọc',type:'path'},
 ne:{label:'Góc trên phải',type:'path'},nw:{label:'Góc trên trái',type:'path'},se:{label:'Góc dưới phải',type:'path'},sw:{label:'Góc dưới trái',type:'path'},
 tUp:{label:'Ngã ba lên',type:'path'},tDown:{label:'Ngã ba xuống',type:'path'},tLeft:{label:'Ngã ba trái',type:'path'},tRight:{label:'Ngã ba phải',type:'path'},cross:{label:'Ngã tư',type:'path'},collapse:{label:'Sập hầm',type:'path'},
 delete:{label:'Phá đường',type:'action'},rotate:{label:'Chuyển hướng',type:'action'},shield:{label:'Gia cố hầm',type:'action'},scout:{label:'Thăm dò rương',type:'action'}
};
const make=(kind:PathKind|ActionKind,rotation=0):Card=>({id:uid(),kind,label:defs[kind].label,type:defs[kind].type,rotation});
const add=(arr:Card[],kind:PathKind|ActionKind,count:number)=>{for(let i=0;i<count;i++)arr.push(make(kind,kind==='collapse'?Math.floor(Math.random()*4)*90:0))};
const shuffle=<T,>(items:T[])=>{const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export const createDeck=()=>{const d:Card[]=[];add(d,'h',13);add(d,'v',7);(['ne','nw','se','sw'] as PathKind[]).forEach(k=>add(d,k,5));(['tUp','tDown','tLeft','tRight'] as PathKind[]).forEach(k=>add(d,k,3));add(d,'cross',5);add(d,'collapse',6);add(d,'delete',7);add(d,'shield',4);add(d,'rotate',4);add(d,'scout',4);return shuffle(d)};
const draw=(deck:Card[],n:number)=>deck.splice(0,Math.min(n,deck.length));

export const dirs=(kind:PathKind,rotation=0):Direction[]=>{const base:Record<PathKind,Direction[]>={h:['L','R'],v:['U','D'],ne:['U','R'],nw:['U','L'],se:['D','R'],sw:['D','L'],tUp:['L','R','U'],tDown:['L','R','D'],tLeft:['U','D','L'],tRight:['U','D','R'],cross:['U','R','D','L'],collapse:['L']};const turns=((rotation%360)+360)%360/90;const order:Direction[]=['U','R','D','L'];return base[kind].map(d=>order[(order.indexOf(d)+turns)%4])};
const opposite:Record<Direction,Direction>={L:'R',R:'L',U:'D',D:'U'};
const delta:Record<Direction,[number,number]>={L:[0,-1],R:[0,1],U:[-1,0],D:[1,0]};
const inBoard=(m:MapConfig,r:number,c:number)=>r>=0&&r<m.rows&&c>=0&&c<m.cols;
const key=(r:number,c:number)=>`${r},${c}`;
const entranceCell=(m:MapConfig):[number,number,Direction]=>m.entrance.side==='left'?[m.entrance.row!,0,'L']:m.entrance.side==='right'?[m.entrance.row!,m.cols-1,'R']:m.entrance.side==='top'?[0,m.entrance.col!,'U']:[m.rows-1,m.entrance.col!,'D'];
const objectiveCell=(m:MapConfig,o:ObjectivePoint):[number,number,Direction]=>o.side==='left'?[o.row!,0,'L']:o.side==='right'?[o.row!,m.cols-1,'R']:o.side==='top'?[0,o.col!,'U']:[m.rows-1,o.col!,'D'];

const hasGeometricRoute=(map:MapConfig,obstacles:Set<string>)=>{const[sr,sc]=entranceCell(map),q:Array<[number,number]>=[[sr,sc]],seen=new Set([key(sr,sc)]);while(q.length){const[r,c]=q.shift()!;if(map.objectives.some(o=>{const[or,oc]=objectiveCell(map,o);return or===r&&oc===c}))return true;for(const[dr,dc]of Object.values(delta)){const nr=r+dr,nc=c+dc,k=key(nr,nc);if(inBoard(map,nr,nc)&&!obstacles.has(k)&&!seen.has(k)){seen.add(k);q.push([nr,nc])}}}return false};
export const generateObstacles=(map:MapConfig)=>{const candidates:Array<[number,number]>=[];for(let r=0;r<map.rows;r++)for(let c=map.obstacleMinCol;c<=Math.min(map.obstacleMaxCol,map.cols-1);c++)candidates.push([r,c]);for(let attempt=0;attempt<300;attempt++){const picked:Array<[number,number]>=[];for(const spot of shuffle(candidates)){if(picked.length>=map.obstacleCount)break;if(picked.every(([r,c])=>Math.abs(r-spot[0])+Math.abs(c-spot[1])>1))picked.push(spot)}const set=new Set(picked.map(([r,c])=>key(r,c)));if(picked.length===map.obstacleCount&&hasGeometricRoute(map,set))return [...set]}return [key(0,3),key(2,6),key(4,9)]};

export const reachableFromEntrance=(board:Cell[][],map:MapConfig=GOLD_MINE_MAP):Set<string>=>{const reachable=new Set<string>();const[sr,sc,sd]=entranceCell(map);const start=board[sr]?.[sc];if(!start?.card||start.card.type!=='path'||!dirs(start.card.kind as PathKind,start.card.rotation).includes(sd))return reachable;const q:Array<[number,number]>=[[sr,sc]];reachable.add(key(sr,sc));while(q.length){const[r,c]=q.shift()!,cell=board[r][c];if(!cell?.card||cell.card.type!=='path')continue;for(const d of dirs(cell.card.kind as PathKind,cell.card.rotation)){const[dr,dc]=delta[d],nr=r+dr,nc=c+dc;if(!inBoard(map,nr,nc))continue;const n=board[nr][nc],k=key(nr,nc);if(n?.card.type==='path'&&dirs(n.card.kind as PathKind,n.card.rotation).includes(opposite[d])&&!reachable.has(k)){reachable.add(k);q.push([nr,nc])}}}return reachable};

export const isValidPlacement=(board:Cell[][],card:Card,row:number,col:number,map:MapConfig=GOLD_MINE_MAP,obstacles:string[]=[])=>{if(card.type!=='path'||board[row]?.[col]||obstacles.includes(key(row,col)))return false;const own=dirs(card.kind as PathKind,card.rotation),reachable=reachableFromEntrance(board,map);let live=false;for(const d of ['U','R','D','L'] as Direction[]){const[dr,dc]=delta[d],nr=row+dr,nc=col+dc,opens=own.includes(d);if(!inBoard(map,nr,nc)){const[eR,eC,eD]=entranceCell(map);const isEntrance=row===eR&&col===eC&&d===eD;const isObjective=map.objectives.some(o=>{const[or,oc,od]=objectiveCell(map,o);return row===or&&col===oc&&d===od});if(isEntrance){if(!opens)return false;live=true}else if(!isObjective&&opens)return false;continue}const neighbor=board[nr][nc];if(neighbor?.card.type==='path'){const match=dirs(neighbor.card.kind as PathKind,neighbor.card.rotation).includes(opposite[d]);if(opens!==match)return false;if(opens&&match&&reachable.has(key(nr,nc)))live=true}}return live};

const refill=(s:GameState,p:Player)=>{if(s.deck.length)p.hand.push(...draw(s.deck,1))};
const advance=(s:GameState)=>{s.turns++;if(!s.deck.length&&s.players.every(p=>p.hand.length===0)){s.winner='wolves';s.logs.unshift('Bộ bài đã cạn. Phe Sói chiến thắng.');return}for(let i=1;i<=s.players.length;i++){const next=(s.turn+i)%s.players.length,p=s.players[next];if(p.blockedTurns>0){p.blockedTurns--;s.logs.unshift(`${p.name} bị chặn và mất lượt.`);continue}s.turn=next;return}};
const resolveTreasures=(s:GameState)=>{const reachable=reachableFromEntrance(s.board,s.map);for(const o of s.map.objectives){const[r,c,d]=objectiveCell(s.map,o),cell=s.board[r]?.[c],t=s.treasures.find(x=>x.id===o.id);if(t&&!t.revealed&&reachable.has(key(r,c))&&cell?.card.type==='path'&&dirs(cell.card.kind as PathKind,cell.card.rotation).includes(d)){t.revealed=true;if(t.isGold){s.winner='miners';s.logs.unshift(`${o.label} chứa vàng thật — Thợ đào chiến thắng!`)}else s.logs.unshift(`${o.label} chỉ có đá. Trận đấu tiếp tục!`)}}};
const playerBase=(id:string,name:string,role:Role,isBot:boolean,avatar:string,hand:Card[]):Player=>({id,name,role,isBot,avatar,hand,score:0,blockedTurns:0,specialUsed:{block:false,revive:false,swap:false}});

export const newGame=(humanName='Bạn',botCount=5,map=GOLD_MINE_MAP):GameState=>{const total=Math.max(6,Math.min(8,botCount+1)),actualBots=total-1,deck=createDeck(),names=['Digger Bot','Luna','Búa Sắt','Mắt Đỏ','Râu Vàng','Đá Xám','Mỏ Neo'],roles=shuffle([...Array(total-2).fill('miner'),...Array(2).fill('wolf')]) as Role[];const players=[playerBase('human',humanName,roles[0],false,'human',draw(deck,5)),...Array.from({length:actualBots},(_,i)=>playerBase(`bot-${i}`,names[i]||`AI ${i+1}`,roles[i+1],true,`bot-${i}`,draw(deck,5)))];const treasureFlags=shuffle([true,false,false]);return{map,board:Array.from({length:map.rows},()=>Array<Cell>(map.cols).fill(null)),obstacles:generateObstacles(map),players,treasures:map.objectives.map((o,i)=>({id:o.id,revealed:false,isGold:treasureFlags[i]??false,peekedBy:[]})),deck,discardPile:[],turn:0,logs:['Trận đấu đã bắt đầu.'],winner:null,turns:0}};

export const placeCard=(state:GameState,playerIndex:number,cardIndex:number,row:number,col:number):GameState=>{const card0=state.players[playerIndex]?.hand[cardIndex];if(state.winner||state.turn!==playerIndex||!card0||!isValidPlacement(state.board,card0,row,col,state.map,state.obstacles))return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],card=p.hand.splice(cardIndex,1)[0];s.board[row][col]={card,owner:p.id};refill(s,p);p.score++;s.logs.unshift(`${p.name} đặt ${card.label} tại ${String.fromCharCode(65+col)}${row+1}.`);resolveTreasures(s);if(!s.winner)advance(s);return s};
const allEdgesValid=(board:Cell[][],map:MapConfig,row:number,col:number)=>{const cell=board[row][col];if(!cell?.card||cell.card.type!=='path')return false;const own=dirs(cell.card.kind as PathKind,cell.card.rotation);for(const d of ['U','R','D','L'] as Direction[]){const[dr,dc]=delta[d],nr=row+dr,nc=col+dc;if(!inBoard(map,nr,nc))continue;const n=board[nr][nc];if(n?.card.type==='path'&&own.includes(d)!==dirs(n.card.kind as PathKind,n.card.rotation).includes(opposite[d]))return false}return true};
export const useAction=(state:GameState,playerIndex:number,cardIndex:number,row:number,col:number):GameState=>{if(state.winner||state.turn!==playerIndex||state.obstacles.includes(key(row,col)))return state;const original=state.players[playerIndex]?.hand[cardIndex];if(!original||original.type!=='action'||original.kind==='scout')return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],card=p.hand[cardIndex],target=s.board[row]?.[col];if(card.kind==='delete'){if(!target||target.shield)return state;s.board[row][col]=null}else if(card.kind==='shield'){if(!target||target.shield)return state;target.shield=true}else if(card.kind==='rotate'){if(!target||target.shield||target.card.type!=='path')return state;target.card.rotation=(target.card.rotation+90)%360;if(!allEdgesValid(s.board,s.map,row,col))return state}else return state;p.hand.splice(cardIndex,1);s.discardPile.push(card);refill(s,p);s.logs.unshift(card.kind==='delete'&&p.role==='wolf'?'Một đoạn đường đã bị phá bí ẩn.':`${p.name} dùng ${card.label} tại ${String.fromCharCode(65+col)}${row+1}.`);resolveTreasures(s);if(!s.winner)advance(s);return s};
export const scoutTreasure=(state:GameState,playerIndex:number,cardIndex:number,treasureId:string):GameState=>{if(state.winner||state.turn!==playerIndex)return state;const original=state.players[playerIndex]?.hand[cardIndex],treasure=state.treasures.find(t=>t.id===treasureId);if(!original||original.kind!=='scout'||!treasure||treasure.revealed)return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],card=p.hand.splice(cardIndex,1)[0],t=s.treasures.find(x=>x.id===treasureId)!;t.peekedBy.push(p.id);s.discardPile.push(card);refill(s,p);s.logs.unshift(`${p.name} đã bí mật thăm dò một rương.`);advance(s);return s};
export const discardCard=(state:GameState,playerIndex:number,cardIndex:number):GameState=>{if(state.winner||state.turn!==playerIndex)return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],card=p?.hand.splice(cardIndex,1)[0];if(!card)return state;s.discardPile.push(card);refill(s,p);s.logs.unshift(`${p.name} bỏ một lá và kết thúc lượt.`);advance(s);return s};

export const useBlock=(state:GameState,playerIndex:number,targetIndex:number):GameState=>{if(state.winner||state.turn!==playerIndex||playerIndex===targetIndex)return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],target=s.players[targetIndex];if(!target||p.specialUsed.block)return state;p.specialUsed.block=true;target.blockedTurns=Math.max(1,target.blockedTurns+1);s.logs.unshift(`${p.name} đã dùng lá Chặn lên ${target.name}.`);advance(s);return s};
export const useRevive=(state:GameState,playerIndex:number,targetIndex:number):GameState=>{if(state.winner||state.turn!==playerIndex)return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],target=s.players[targetIndex];if(!target||p.specialUsed.revive||target.blockedTurns<=0)return state;p.specialUsed.revive=true;target.blockedTurns=0;s.logs.unshift(`${p.name} đã hồi sinh lượt chơi cho ${target.name}.`);advance(s);return s};
export const useSwap=(state:GameState,playerIndex:number,myCardIndex:number,targetIndex:number,targetCardIndex:number):GameState=>{if(state.winner||state.turn!==playerIndex||playerIndex===targetIndex)return state;const s=structuredClone(state) as GameState,p=s.players[playerIndex],target=s.players[targetIndex];if(p.specialUsed.swap||!p.hand[myCardIndex]||!target?.hand[targetCardIndex])return state;[p.hand[myCardIndex],target.hand[targetCardIndex]]=[target.hand[targetCardIndex],p.hand[myCardIndex]];p.specialUsed.swap=true;s.logs.unshift(`${p.name} đã bí mật đổi một lá bài với ${target.name}.`);advance(s);return s};

export const botMove=(state:GameState):GameState=>{const idx=state.turn,p=state.players[idx];if(!p?.isBot||state.winner)return state;const candidates:Array<[number,number,number]>=[];p.hand.forEach((card,i)=>{if(card.type==='path')for(let r=0;r<state.map.rows;r++)for(let c=0;c<state.map.cols;c++)if(isValidPlacement(state.board,card,r,c,state.map,state.obstacles))candidates.push([i,r,c])});if(p.role==='wolf'){const deleteIndex=p.hand.findIndex(c=>c.kind==='delete');const targets:Array<[number,number]>=[];for(let r=0;r<state.map.rows;r++)for(let c=0;c<state.map.cols;c++)if(state.board[r][c]&&!state.board[r][c]?.shield)targets.push([r,c]);if(deleteIndex>=0&&targets.length&&Math.random()<.55){const[r,c]=targets[Math.floor(Math.random()*targets.length)];return useAction(state,idx,deleteIndex,r,c)}}if(candidates.length){const score=([,r,c]:[number,number,number])=>p.role==='miner'?c+Math.random()*2:-c+Math.random()*5;const pick=[...candidates].sort((a,b)=>score(b)-score(a))[0];return placeCard(state,idx,pick[0],pick[1],pick[2])}const actionIndex=p.hand.findIndex(c=>c.kind==='scout');if(actionIndex>=0){const hidden=state.treasures.find(t=>!t.revealed&&!t.peekedBy.includes(p.id));if(hidden)return scoutTreasure(state,idx,actionIndex,hidden.id)}return discardCard(state,idx,Math.max(0,Math.floor(Math.random()*p.hand.length)))};
