import { FormEvent, useCallback, useEffect, useState } from 'react';
import { addDoc, collection, deleteDoc, doc, getDoc, getDocs, limit, orderBy, query, serverTimestamp, setDoc, updateDoc, writeBatch } from 'firebase/firestore';
import { Activity, ChevronLeft, ChevronRight, Coins, Edit3, Gauge, Plus, Search, ShieldAlert, Trash2, Users, Warehouse, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { db } from '../lib/firebase';
import { disbandGuild, Guild } from '../lib/guilds';
import { expForLevel, levelFromExp, MAX_LEVEL } from '../lib/progression';
import { ADMIN_UID, nameSlug } from '../lib/slugs';

type AdminRoom={id:string;name:string;hostName?:string;code?:string;status?:'waiting'|'started';visibility?:'public'|'private';maxPlayers?:number;players?:unknown[]};
type AdminUser={uid:string;displayName:string;email?:string;photoURL?:string;rank?:string;coins:number;exp:number;guildName?:string};
type AdminGuildMember={uid:string;displayName:string;photoURL?:string;role:'owner'|'officer'|'member';title?:string;goldContribution?:number;contribution?:number};
type ConfirmState={title:string;message:string;confirmLabel:string;action:()=>Promise<void>};
type GuildDraft={id?:string;name:string;tag:string;description:string;ownerId:string};
type RoomDraft={id:string;name:string;status:'waiting'|'started';visibility:'public'|'private';maxPlayers:number;playerCount:number;code?:string};
type AdminLog={id:string;adminUid:string;adminName:string;message:string;createdAt?:{toDate?:()=>Date}};
type UserDraft={uid:string;displayName:string;email:string;coins:number;level:number};
type MemberDraft={guildId:string;guildName:string;member:AdminGuildMember};

const emptyGuild:GuildDraft={name:'',tag:'',description:'',ownerId:''};
const deleteChildren=async(parent:[string,string],subcollections:string[])=>{
 if(!db)return;
 for(const child of subcollections){
  const snap=await getDocs(collection(db,parent[0],parent[1],child));
  if(snap.empty)continue;
  const batch=writeBatch(db);snap.docs.forEach(item=>batch.delete(item.ref));await batch.commit();
 }
};

export default function Admin(){
 const{profile}=useAuth();
 const[rooms,setRooms]=useState<AdminRoom[]>([]),[guilds,setGuilds]=useState<Guild[]>([]),[users,setUsers]=useState<AdminUser[]>([]),[logs,setLogs]=useState<AdminLog[]>([]);
 const[message,setMessage]=useState(''),[confirmState,setConfirmState]=useState<ConfirmState|null>(null),[guildDraft,setGuildDraft]=useState<GuildDraft|null>(null),[roomDraft,setRoomDraft]=useState<RoomDraft|null>(null),[userDraft,setUserDraft]=useState<UserDraft|null>(null),[memberDraft,setMemberDraft]=useState<MemberDraft|null>(null);
 const[selectedGuild,setSelectedGuild]=useState<Guild|null>(null),[guildMembers,setGuildMembers]=useState<AdminGuildMember[]>([]),[membersLoading,setMembersLoading]=useState(false);
 const[activeTab,setActiveTab]=useState<'rooms'|'guilds'|'users'|'logs'>('rooms'),[adminSearch,setAdminSearch]=useState('');
 const[pages,setPages]=useState<Record<'rooms'|'guilds'|'users'|'logs',number>>({rooms:1,guilds:1,users:1,logs:1});
 const[selectedRoomIds,setSelectedRoomIds]=useState<string[]>([]);
 const load=useCallback(async()=>{if(!db||profile?.uid!==ADMIN_UID)return;const[roomSnap,guildSnap,userSnap,logSnap]=await Promise.all([getDocs(collection(db,'rooms')),getDocs(collection(db,'guilds')),getDocs(collection(db,'users')),getDocs(query(collection(db,'adminLogs'),orderBy('createdAt','desc'),limit(200)))]);const loadedUsers=userSnap.docs.map(item=>({coins:0,exp:0,uid:item.id,...item.data()} as AdminUser)),userNames=new Map(loadedUsers.map(item=>[item.uid,item.displayName])),loadedGuilds=guildSnap.docs.map(item=>{const guild={id:item.id,...item.data()} as Guild;return{...guild,ownerName:guild.ownerName||userNames.get(guild.ownerId)||'Không xác định'}}),memberSnaps=await Promise.all(loadedGuilds.map(guild=>getDocs(collection(db!,'guilds',guild.id,'members')))),guildByUser=new Map<string,string>();memberSnaps.forEach((snap,index)=>snap.docs.forEach(member=>guildByUser.set(member.id,`${loadedGuilds[index].tag?`[${loadedGuilds[index].tag}] `:''}${loadedGuilds[index].name}`)));setRooms(roomSnap.docs.map(item=>({id:item.id,...item.data()} as AdminRoom)));setGuilds(loadedGuilds);setUsers(loadedUsers.map(user=>({...user,guildName:guildByUser.get(user.uid)||'Chưa có Guild'})));setLogs(logSnap.docs.map(item=>({id:item.id,...item.data()} as AdminLog)))},[profile?.uid]);
 useEffect(()=>{void load()},[load]);
 if(profile?.uid!==ADMIN_UID)return <section className="center-page"><div className="auth-card"><ShieldAlert/><h1>KHÔNG CÓ QUYỀN</h1></div></section>;

 const recordLog=async(message:string)=>{if(!db||!profile)return;await addDoc(collection(db,'adminLogs'),{adminUid:profile.uid,adminName:profile.displayName,message:message.slice(0,500),createdAt:serverTimestamp()})};
 const act=async(action:()=>Promise<void>,success:string,logMessage=success)=>{try{await action();try{await recordLog(logMessage)}catch{}setMessage(success);await load()}catch(error){setMessage(error instanceof Error?error.message:'Không thể thực hiện thao tác.')}};
 const removeRoom=async(id:string)=>{if(!db)return;await deleteChildren(['rooms',id],['messages']);await deleteDoc(doc(db,'rooms',id))};
 const saveRoom=async(event:FormEvent)=>{event.preventDefault();if(!db||!roomDraft)return;const name=roomDraft.name.trim().replace(/\s+/g,' ');if(name.length<3||name.length>40)throw new Error('Tên phòng phải từ 3 đến 40 ký tự.');if(roomDraft.maxPlayers<roomDraft.playerCount)throw new Error(`Phòng đang có ${roomDraft.playerCount} người, không thể giảm giới hạn thấp hơn.`);await updateDoc(doc(db,'rooms',roomDraft.id),{name,status:roomDraft.status,visibility:roomDraft.visibility,maxPlayers:roomDraft.maxPlayers,updatedAt:serverTimestamp()})};
 const removeUser=async(uid:string)=>{if(!db||uid===ADMIN_UID)throw new Error('Không thể xóa tài khoản admin.');await deleteChildren(['users',uid],['friends','friendRequests','roomInvites','matchHistory','completedMatches']);await setDoc(doc(db,'bannedUsers',uid),{deletedBy:ADMIN_UID,deletedAt:serverTimestamp()});await deleteDoc(doc(db,'users',uid))};
 const openGuildMembers=async(guild:Guild)=>{if(!db)return;setSelectedGuild(guild);setMembersLoading(true);try{const snap=await getDocs(collection(db,'guilds',guild.id,'members'));setGuildMembers(snap.docs.map(item=>({uid:item.id,...item.data()} as AdminGuildMember)))}finally{setMembersLoading(false)}};
 const saveUser=async(event:FormEvent)=>{event.preventDefault();if(!db||!userDraft)return;const displayName=userDraft.displayName.trim().replace(/\s+/g,' ').slice(0,60);if(displayName.length<2)throw new Error('Tên người chơi phải có ít nhất 2 ký tự.');const coins=Math.max(0,Math.min(1_000_000,Math.floor(Number(userDraft.coins)||0))),level=Math.max(1,Math.min(MAX_LEVEL,Math.floor(Number(userDraft.level)||1))),exp=expForLevel(level);await updateDoc(doc(db,'users',userDraft.uid),{displayName,coins,exp,updatedAt:serverTimestamp()})};
 const saveMember=async(event:FormEvent)=>{event.preventDefault();if(!db||!memberDraft)return;const {guildId,member}=memberDraft;if(member.role==='owner')throw new Error('Hãy đổi chủ Guild trong phần chỉnh sửa Guild.');const title=String(member.title||'').trim().slice(0,30),goldContribution=Math.max(0,Math.floor(Number(member.goldContribution)||0));await updateDoc(doc(db,'guilds',guildId,'members',member.uid),{role:member.role,title,goldContribution,updatedAt:serverTimestamp()})};
 const removeGuildMember=async(guild:Guild,member:AdminGuildMember)=>{if(!db)return;if(member.role==='owner'||member.uid===guild.ownerId)throw new Error('Không thể xóa chủ Guild. Hãy chuyển chủ trước.');await deleteDoc(doc(db,'guilds',guild.id,'members',member.uid));await updateDoc(doc(db,'guilds',guild.id),{memberCount:Math.max(0,guild.memberCount-1),updatedAt:serverTimestamp()})};
 const saveGuild=async(event:FormEvent)=>{event.preventDefault();if(!db||!guildDraft)return;const safeName=guildDraft.name.trim().replace(/\s+/g,' '),safeTag=guildDraft.tag.trim().toUpperCase(),slug=nameSlug(safeName),owner=users.find(item=>item.uid===guildDraft.ownerId);if(safeName.length<3||safeName.length>12)throw new Error('Tên guild phải từ 3 đến 12 ký tự.');if(safeTag.length<2||safeTag.length>5)throw new Error('Tag guild phải từ 2 đến 5 ký tự.');if(!owner)throw new Error('Hãy chọn chủ guild.');
  const duplicate=guilds.some(item=>item.id!==guildDraft.id&&nameSlug(item.name)===slug);if(duplicate)throw new Error('Tên guild đã tồn tại.');
  if(guildDraft.id){
   const current=guilds.find(item=>item.id===guildDraft.id);if(!current)throw new Error('Guild không còn tồn tại.');
   const newOwnerRef=doc(db,'guilds',current.id,'members',owner.uid),newOwnerSnap=await getDoc(newOwnerRef),ownerChanged=current.ownerId!==owner.uid;
   const batch=writeBatch(db);batch.update(doc(db,'guilds',current.id),{name:safeName,slug,tag:safeTag,description:guildDraft.description.trim().slice(0,160),ownerId:owner.uid,ownerName:owner.displayName,memberCount:current.memberCount+(ownerChanged&&!newOwnerSnap.exists()?1:0),updatedAt:serverTimestamp()});
   if(ownerChanged){batch.set(doc(db,'guilds',current.id,'members',current.ownerId),{role:'member',title:'Thành viên'},{merge:true});batch.set(newOwnerRef,{uid:owner.uid,displayName:owner.displayName,photoURL:owner.photoURL||'',rank:owner.rank||'Sắt IV',equipped:newOwnerSnap.data()?.equipped||{},role:'owner',title:'Hội trưởng',contribution:Number(newOwnerSnap.data()?.contribution||0),warPoints:Number(newOwnerSnap.data()?.warPoints||0),joinedAt:newOwnerSnap.data()?.joinedAt||serverTimestamp()},{merge:true})}
   if(nameSlug(current.name)!==slug){batch.delete(doc(db,'guildNames',nameSlug(current.name)));batch.set(doc(db,'guildNames',slug),{guildId:current.id,name:safeName,ownerId:owner.uid,createdAt:serverTimestamp()})}else batch.set(doc(db,'guildNames',slug),{guildId:current.id,name:safeName,ownerId:owner.uid},{merge:true});
   await batch.commit();
  }else{
   const guildRef=doc(db,'guilds',slug),batch=writeBatch(db);batch.set(guildRef,{name:safeName,slug,tag:safeTag,description:guildDraft.description.trim().slice(0,160),ownerId:owner.uid,ownerName:owner.displayName,memberCount:1,totalContribution:0,totalWarPoints:0,power:0,treasury:0,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});batch.set(doc(db,'guildNames',slug),{guildId:slug,name:safeName,ownerId:owner.uid,createdAt:serverTimestamp()});batch.set(doc(guildRef,'members',owner.uid),{uid:owner.uid,displayName:owner.displayName,photoURL:owner.photoURL||'',rank:owner.rank||'Sắt IV',equipped:{},role:'owner',title:'Hội trưởng',contribution:0,warPoints:0,joinedAt:serverTimestamp()});await batch.commit();
  }
 };
 const submitGuild=(event:FormEvent)=>{const label=guildDraft?.id?`Đã cập nhật Guild “${guildDraft.name}”.`:`Đã thêm Guild “${guildDraft?.name||''}”.`;void act(async()=>{await saveGuild(event);setGuildDraft(null)},label)};
 const submitRoom=(event:FormEvent)=>{const label=`Đã cập nhật phòng “${roomDraft?.name||''}”.`;void act(async()=>{await saveRoom(event);setRoomDraft(null)},label)};
 const submitUser=(event:FormEvent)=>{const label=`Đã cập nhật người chơi “${userDraft?.displayName||''}”.`;void act(async()=>{await saveUser(event);setUserDraft(null)},label)};
 const submitMember=(event:FormEvent)=>{const label=`Đã cập nhật thành viên “${memberDraft?.member.displayName||''}”.`;void act(async()=>{await saveMember(event);setMemberDraft(null);if(selectedGuild)await openGuildMembers(selectedGuild)},label)};
 const ask=(state:ConfirmState)=>setConfirmState(state);
 const term=adminSearch.trim().toLocaleLowerCase('vi'),visibleRooms=term?rooms.filter(room=>(room.name+' '+(room.hostName||room.id)).toLocaleLowerCase('vi').includes(term)):rooms,visibleGuilds=term?guilds.filter(guild=>(guild.name+' '+guild.tag+' '+(guild.ownerName||'')).toLocaleLowerCase('vi').includes(term)):guilds,visibleUsers=term?users.filter(user=>(user.displayName+' '+(user.email||user.uid)).toLocaleLowerCase('vi').includes(term)):users,visibleLogs=term?logs.filter(log=>(log.adminName+' '+log.message).toLocaleLowerCase('vi').includes(term)):logs;
 const pageSize=15,currentItems=activeTab==='rooms'?visibleRooms:activeTab==='guilds'?visibleGuilds:activeTab==='users'?visibleUsers:visibleLogs,pageCount=Math.max(1,Math.ceil(currentItems.length/pageSize)),currentPage=Math.min(pages[activeTab],pageCount),pageStart=(currentPage-1)*pageSize,pagedRooms=visibleRooms.slice(pageStart,pageStart+pageSize),pagedGuilds=visibleGuilds.slice(pageStart,pageStart+pageSize),pagedUsers=visibleUsers.slice(pageStart,pageStart+pageSize),pagedLogs=visibleLogs.slice(pageStart,pageStart+pageSize);
 const changePage=(page:number)=>setPages(current=>({...current,[activeTab]:Math.max(1,Math.min(pageCount,page))}));
 const pageRoomIds=pagedRooms.map(room=>room.id),allPageRoomsSelected=pageRoomIds.length>0&&pageRoomIds.every(id=>selectedRoomIds.includes(id));
 const togglePageRooms=()=>setSelectedRoomIds(current=>allPageRoomsSelected?current.filter(id=>!pageRoomIds.includes(id)):Array.from(new Set([...current,...pageRoomIds])));
 const toggleRoom=(id:string)=>setSelectedRoomIds(current=>current.includes(id)?current.filter(value=>value!==id):[...current,id]);

 return <section className="admin-page app-page">
  <header><ShieldAlert/><div><span>QUYỀN QUẢN TRỊ</span><h1>ADMIN CONTROL</h1></div></header>
  {message&&<button className="guild-message" onClick={()=>setMessage('')}>{message}<X/></button>}
  <nav className="admin-tabs app-tabs"><button className={activeTab==='rooms'?'active':''} onClick={()=>{setActiveTab('rooms');setAdminSearch('')}}><Warehouse/><span><b>QUẢN LÝ PHÒNG</b><small>Phòng đang hoạt động</small></span><em>{rooms.length}</em></button><button className={activeTab==='guilds'?'active':''} onClick={()=>{setActiveTab('guilds');setAdminSearch('')}}><ShieldAlert/><span><b>QUẢN LÝ GUILD</b><small>Thông tin và thành viên</small></span><em>{guilds.length}</em></button><button className={activeTab==='users'?'active':''} onClick={()=>{setActiveTab('users');setAdminSearch('')}}><Users/><span><b>QUẢN LÝ USER</b><small>Vàng, cấp và tài khoản</small></span><em>{users.length}</em></button><button className={activeTab==='logs'?'active':''} onClick={()=>{setActiveTab('logs');setAdminSearch('')}}><Activity/><span><b>NHẬT KÝ ADMIN</b><small>Lịch sử mọi thao tác</small></span><em>{logs.length}</em></button></nav>
  <section className="panel app-section admin-workspace">
   <header><div>{activeTab==='rooms'?<Warehouse/>:activeTab==='guilds'?<ShieldAlert/>:activeTab==='users'?<Users/>:<Activity/>}<span><small>ADMIN CONTROL</small><h2>{activeTab==='rooms'?'DANH SÁCH PHÒNG':activeTab==='guilds'?'DANH SÁCH GUILD':activeTab==='users'?'DANH SÁCH NGƯỜI CHƠI':'NHẬT KÝ THAO TÁC'}</h2></span></div><label><Search/><input value={adminSearch} onChange={event=>setAdminSearch(event.target.value)} placeholder={activeTab==='rooms'?'Tìm tên phòng...':activeTab==='guilds'?'Tìm Guild hoặc chủ Guild...':activeTab==='users'?'Tìm tên hoặc email...':'Tìm nội dung nhật ký...'}/></label>{activeTab==='guilds'&&<button className="btn btn-primary" onClick={()=>setGuildDraft({...emptyGuild,ownerId:users[0]?.uid||''})}><Plus/> THÊM GUILD</button>}</header>
   <div className="admin-table-head">{activeTab==='rooms'?<><span>PHÒNG</span><span>CHỦ PHÒNG</span><span>THAO TÁC</span></>:activeTab==='guilds'?<><span>GUILD</span><span>CHỦ GUILD</span><span>THÀNH VIÊN</span><span>THAO TÁC</span></>:activeTab==='users'?<><span>NGƯỜI CHƠI</span><span>GUILD</span><span>TÀI SẢN</span><span>CẤP</span><span>THAO TÁC</span></>:<><span>THỜI GIAN</span><span>ADMIN</span><span>NỘI DUNG THAO TÁC</span></>}</div>
   <div className={`admin-table-body ${activeTab}`}>
    {activeTab==='rooms'&&pagedRooms.map(room=><article className={selectedRoomIds.includes(room.id)?'selected':''} key={room.id}><label className="admin-room-check" title="Chọn phòng"><input type="checkbox" checked={selectedRoomIds.includes(room.id)} onChange={()=>toggleRoom(room.id)}/><span/></label><span><b>{room.name}</b><small>{room.code?`#${room.code} · `:''}{room.id}</small></span><span>{room.hostName||'Không xác định'}</span><div><button className="admin-icon-button" title="Chỉnh sửa phòng" aria-label={`Chỉnh sửa phòng ${room.name}`} onClick={()=>setRoomDraft({id:room.id,name:room.name,status:room.status||'waiting',visibility:room.visibility||'public',maxPlayers:room.maxPlayers||6,playerCount:room.players?.length||0,code:room.code})}><Edit3/></button><button className="admin-icon-button danger" title="Xóa phòng" aria-label={`Xóa phòng ${room.name}`} onClick={()=>ask({title:'XÓA PHÒNG',message:`Xóa phòng “${room.name}” và toàn bộ tin nhắn?`,confirmLabel:'XÓA PHÒNG',action:()=>removeRoom(room.id)})}><Trash2/></button></div></article>)}
    {activeTab==='guilds'&&pagedGuilds.map(guild=><article key={guild.id}><span><b>{guild.tag&&`[${guild.tag}] `}{guild.name}</b><small>{guild.description||'Chưa có giới thiệu'}</small></span><span><b>{guild.ownerName||users.find(user=>user.uid===guild.ownerId)?.displayName||'Không xác định'}</b><small>{guild.ownerId}</small></span><button className="admin-member-count" title="Xem danh sách thành viên" onClick={()=>void openGuildMembers(guild)}><Users/><b>{guild.memberCount}</b></button><div><button className="admin-icon-button" title="Danh sách thành viên" aria-label={`Quản lý thành viên ${guild.name}`} onClick={()=>void openGuildMembers(guild)}><Users/></button><button className="admin-icon-button" title="Chỉnh sửa Guild" aria-label={`Chỉnh sửa Guild ${guild.name}`} onClick={()=>setGuildDraft({id:guild.id,name:guild.name,tag:guild.tag,description:guild.description,ownerId:guild.ownerId})}><Edit3/></button><button className="admin-icon-button danger" title="Xóa Guild" aria-label={`Xóa Guild ${guild.name}`} onClick={()=>ask({title:'XÓA GUILD',message:`Giải tán “${guild.name}” và xóa toàn bộ dữ liệu?`,confirmLabel:'XÓA GUILD',action:()=>disbandGuild(guild.id)})}><Trash2/></button></div></article>)}
    {activeTab==='users'&&pagedUsers.map(user=><article key={user.uid}><span><b>{user.displayName}</b><small>{user.email||user.uid}</small></span><span className="admin-user-guild">{user.guildName}</span><strong><Coins/>{user.coins.toLocaleString('vi-VN')}</strong><strong><Gauge/>Lv.{levelFromExp(user.exp)}</strong><div><button className="admin-icon-button" title="Chỉnh sửa người dùng" aria-label={`Chỉnh sửa ${user.displayName}`} onClick={()=>setUserDraft({uid:user.uid,displayName:user.displayName,email:user.email||'',coins:user.coins,level:levelFromExp(user.exp)})}><Edit3/></button><button disabled={user.uid===ADMIN_UID} className="admin-icon-button danger" title="Xóa người dùng" aria-label={`Xóa người dùng ${user.displayName}`} onClick={()=>ask({title:'XÓA USER',message:`Xóa dữ liệu và khóa tài khoản “${user.displayName}”?`,confirmLabel:'XÓA USER',action:()=>removeUser(user.uid)})}><Trash2/></button></div></article>)}
    {activeTab==='logs'&&pagedLogs.map(log=><article key={log.id}><time>{log.createdAt?.toDate?.().toLocaleString('vi-VN')||'Vừa xong'}</time><span><b>{log.adminName}</b><small>{log.adminUid}</small></span><p>{log.message}</p></article>)}
    {!((activeTab==='rooms'?visibleRooms:activeTab==='guilds'?visibleGuilds:activeTab==='users'?visibleUsers:visibleLogs).length)&&<div className="admin-empty"><Search/><b>KHÔNG TÌM THẤY DỮ LIỆU</b><span>Thử lại với từ khóa khác.</span></div>}
   </div>
   {activeTab==='rooms'&&pagedRooms.length>0&&<div className="admin-room-bulk"><label><input type="checkbox" checked={allPageRoomsSelected} onChange={togglePageRooms}/><span/>CHỌN CẢ TRANG ({pagedRooms.length})</label><small>{selectedRoomIds.length} phòng đã chọn</small><button disabled={!selectedRoomIds.length} onClick={()=>ask({title:'XÓA NHIỀU PHÒNG',message:`Xóa ${selectedRoomIds.length} phòng đã chọn và toàn bộ tin nhắn?`,confirmLabel:'XÓA TẤT CẢ',action:async()=>{await Promise.all(selectedRoomIds.map(removeRoom));setSelectedRoomIds([])}})}><Trash2/> XÓA ĐÃ CHỌN</button></div>}
   {currentItems.length>0&&<nav className="admin-pagination" aria-label="Phân trang quản trị"><button disabled={currentPage===1} onClick={()=>changePage(currentPage-1)} aria-label="Trang trước"><ChevronLeft/></button><span>TRANG <b>{currentPage}</b> / {pageCount}<small>{pageStart+1}–{Math.min(pageStart+pageSize,currentItems.length)} / {currentItems.length}</small></span><button disabled={currentPage===pageCount} onClick={()=>changePage(currentPage+1)} aria-label="Trang sau"><ChevronRight/></button></nav>}
  </section>
  {roomDraft&&<div className="guild-modal-backdrop" onMouseDown={()=>setRoomDraft(null)}><form className="guild-modal admin-room-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submitRoom}><button type="button" className="guild-close" onClick={()=>setRoomDraft(null)}><X/></button><Edit3/><span>ADMIN CONTROL</span><h2>CHỈNH SỬA PHÒNG</h2><div className="admin-room-meta"><small>MÃ PHÒNG</small><b>{roomDraft.code||roomDraft.id}</b><small>NGƯỜI TRONG PHÒNG</small><b>{roomDraft.playerCount}/{roomDraft.maxPlayers}</b></div><label>Tên phòng<input autoFocus required minLength={3} maxLength={40} value={roomDraft.name} onChange={event=>setRoomDraft({...roomDraft,name:event.target.value})}/></label><div className="admin-room-fields"><label>Trạng thái<select value={roomDraft.status} onChange={event=>setRoomDraft({...roomDraft,status:event.target.value as RoomDraft['status']})}><option value="waiting">Đang chờ</option><option value="started">Đang chơi</option></select></label><label>Hiển thị<select value={roomDraft.visibility} onChange={event=>setRoomDraft({...roomDraft,visibility:event.target.value as RoomDraft['visibility']})}><option value="public">Công khai</option><option value="private">Riêng tư</option></select></label></div><label>Số người tối đa<select value={roomDraft.maxPlayers} onChange={event=>setRoomDraft({...roomDraft,maxPlayers:Number(event.target.value)})}>{[6,7,8].map(count=><option disabled={count<roomDraft.playerCount} value={count} key={count}>{count} người</option>)}</select></label><button className="btn btn-primary btn-wide"><Edit3/> LƯU THAY ĐỔI</button></form></div>}
  {guildDraft&&<div className="guild-modal-backdrop" onMouseDown={()=>setGuildDraft(null)}><form className="guild-modal admin-guild-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submitGuild}><button type="button" className="guild-close" onClick={()=>setGuildDraft(null)}><X/></button><ShieldAlert/><span>ADMIN CONTROL</span><h2>{guildDraft.id?'CHỈNH SỬA GUILD':'THÊM GUILD'}</h2><label>Tên Guild<input required minLength={3} maxLength={12} value={guildDraft.name} onChange={event=>setGuildDraft({...guildDraft,name:event.target.value})}/></label><label>Tag Guild<input required minLength={2} maxLength={5} value={guildDraft.tag} onChange={event=>setGuildDraft({...guildDraft,tag:event.target.value.toUpperCase()})}/></label><label>Chủ Guild<select value={guildDraft.ownerId} onChange={event=>setGuildDraft({...guildDraft,ownerId:event.target.value})}>{users.map(user=><option key={user.uid} value={user.uid}>{user.displayName}</option>)}</select></label><label>Giới thiệu<textarea maxLength={160} value={guildDraft.description} onChange={event=>setGuildDraft({...guildDraft,description:event.target.value})}/></label><button className="btn btn-primary btn-wide">{guildDraft.id?'LƯU THAY ĐỔI':'THÊM GUILD'}</button></form></div>}
  {userDraft&&<div className="guild-modal-backdrop" onMouseDown={()=>setUserDraft(null)}><form className="guild-modal admin-user-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submitUser}><button type="button" className="guild-close" onClick={()=>setUserDraft(null)}><X/></button><Edit3/><span>ADMIN CONTROL</span><h2>CHỈNH SỬA USER</h2><small className="admin-modal-id">UID · {userDraft.uid}</small><label>Tên hiển thị<input required minLength={2} maxLength={60} value={userDraft.displayName} onChange={event=>setUserDraft({...userDraft,displayName:event.target.value})}/></label><label>Email<input type="email" value={userDraft.email} readOnly disabled title="Email được đồng bộ từ tài khoản Google và không thể chỉnh sửa"/></label><div className="admin-number-grid"><label>Vàng<input type="number" min={0} max={1000000} value={userDraft.coins} onChange={event=>setUserDraft({...userDraft,coins:Number(event.target.value)})}/></label><label>Level<input type="number" min={1} max={MAX_LEVEL} value={userDraft.level} onChange={event=>setUserDraft({...userDraft,level:Number(event.target.value)})}/></label></div><button className="btn btn-primary btn-wide"><Edit3/> LƯU THÔNG TIN</button></form></div>}
  {selectedGuild&&<div className="guild-modal-backdrop" onMouseDown={()=>setSelectedGuild(null)}><div className="guild-modal admin-members-modal" onMouseDown={event=>event.stopPropagation()}><button type="button" className="guild-close" onClick={()=>setSelectedGuild(null)}><X/></button><Users/><span>{selectedGuild.tag?`[${selectedGuild.tag}] `:''}{selectedGuild.name}</span><h2>DANH SÁCH THÀNH VIÊN</h2>{membersLoading?<div className="admin-members-empty">ĐANG TẢI...</div>:guildMembers.length?<div className="admin-members-list">{guildMembers.map(member=><article key={member.uid}><span><b>{member.displayName}</b><small>{member.uid}</small></span><em className={`admin-member-role ${member.role}`}>{member.role==='owner'?'CHỦ GUILD':member.role==='officer'?'PHÓ GUILD':'THÀNH VIÊN'}</em><strong><Coins/>{Number(member.goldContribution||0).toLocaleString('vi-VN')}</strong><div><button className="admin-icon-button" disabled={member.role==='owner'} title={member.role==='owner'?'Đổi chủ trong form Guild':'Chỉnh sửa thành viên'} onClick={()=>setMemberDraft({guildId:selectedGuild.id,guildName:selectedGuild.name,member:{...member}})}><Edit3/></button><button className="admin-icon-button danger" disabled={member.role==='owner'} title="Xóa khỏi Guild" onClick={()=>ask({title:'XÓA THÀNH VIÊN',message:`Xóa “${member.displayName}” khỏi Guild “${selectedGuild.name}”?`,confirmLabel:'XÓA THÀNH VIÊN',action:async()=>{await removeGuildMember(selectedGuild,member);await openGuildMembers({...selectedGuild,memberCount:Math.max(0,selectedGuild.memberCount-1)})}})}><Trash2/></button></div></article>)}</div>:<div className="admin-members-empty">GUILD CHƯA CÓ THÀNH VIÊN</div>}</div></div>}
  {memberDraft&&<div className="guild-modal-backdrop admin-nested-modal" onMouseDown={()=>setMemberDraft(null)}><form className="guild-modal admin-member-edit-modal" onMouseDown={event=>event.stopPropagation()} onSubmit={submitMember}><button type="button" className="guild-close" onClick={()=>setMemberDraft(null)}><X/></button><Edit3/><span>{memberDraft.guildName}</span><h2>SỬA THÀNH VIÊN</h2><b className="admin-edit-member-name">{memberDraft.member.displayName}</b><label>Vai trò<select value={memberDraft.member.role} onChange={event=>setMemberDraft({...memberDraft,member:{...memberDraft.member,role:event.target.value as AdminGuildMember['role']}})}><option value="member">Thành viên</option><option value="officer">Phó Guild</option></select></label><label>Danh hiệu<input maxLength={30} value={memberDraft.member.title||''} onChange={event=>setMemberDraft({...memberDraft,member:{...memberDraft.member,title:event.target.value}})}/></label><label>Cống hiến vàng<input type="number" min={0} value={memberDraft.member.goldContribution||0} onChange={event=>setMemberDraft({...memberDraft,member:{...memberDraft.member,goldContribution:Number(event.target.value)}})}/></label><button className="btn btn-primary btn-wide"><Edit3/> LƯU THÀNH VIÊN</button></form></div>}
  {confirmState&&<div className="guild-modal-backdrop guild-confirm-backdrop" onMouseDown={()=>setConfirmState(null)}><div className="guild-modal guild-confirm-modal" onMouseDown={event=>event.stopPropagation()}><span>ADMIN CONTROL</span><h2>{confirmState.title}</h2><p>{confirmState.message}</p><div><button className="btn btn-ghost" onClick={()=>setConfirmState(null)}>HỦY</button><button className="btn btn-danger" onClick={()=>{const current=confirmState;setConfirmState(null);void act(current.action,'Đã thực hiện thao tác.',`${current.title}: ${current.message}`)}}>{confirmState.confirmLabel}</button></div></div></div>}
 </section>;
}
