import { FormEvent, useEffect, useState } from 'react';
import { collection, doc, getDoc, getDocs, limit, query } from 'firebase/firestore';
import { Check, DoorOpen, Search, UserMinus, UserPlus, UserRound, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import PlayerIdentity from '../components/PlayerIdentity';
import { db } from '../lib/firebase';
import { acceptFriendRequest, declineFriendRequest, dismissRoomInvite, FriendRequest, FriendSummary, friendshipStatus, FriendshipStatus, removeFriend, RoomInvite, sendFriendRequest, watchFriendRequests, watchFriends, watchRoomInvites } from '../lib/friends';

export default function Friends(){
 const{profile}=useAuth();const[friends,setFriends]=useState<FriendSummary[]>([]);const[requests,setRequests]=useState<FriendRequest[]>([]);const[invites,setInvites]=useState<RoomInvite[]>([]);const[msg,setMsg]=useState('');
 const[searchText,setSearchText]=useState('');const[results,setResults]=useState<Array<FriendSummary&{relation:FriendshipStatus}>>([]);const[searching,setSearching]=useState(false);const[searched,setSearched]=useState(false);
 useEffect(()=>{if(!profile)return;const stops=[watchFriends(profile.uid,setFriends),watchFriendRequests(profile.uid,setRequests),watchRoomInvites(profile.uid,setInvites)];return()=>stops.forEach(stop=>stop())},[profile?.uid]);
 if(!profile)return null;
 const act=async(action:()=>Promise<void>,message:string)=>{try{await action();setMsg(message)}catch(error:any){setMsg(error?.message||'Không thể thực hiện thao tác.')}};
 const findPlayers=async(e?:FormEvent)=>{e?.preventDefault();const rawTerm=searchText.trim(),term=rawTerm.toLocaleLowerCase('vi');if(!db||term.length<2){setMsg('Nhập ít nhất 2 ký tự tên hoặc UID.');return}setSearching(true);setSearched(true);try{const[snap,exact]=await Promise.all([getDocs(query(collection(db,'users'),limit(100))),getDoc(doc(db,'users',rawTerm))]);const docs=[...snap.docs,...exact.exists()&&!snap.docs.some(item=>item.id===exact.id)?[exact]:[]];const matches=docs.map(item=>{const data=item.data();return{uid:item.id,displayName:String(data.displayName||'Người chơi'),photoURL:String(data.photoURL||''),rank:String(data.rank||'Tân binh'),equipped:data.equipped&&typeof data.equipped==='object'?data.equipped:{}} as FriendSummary}).filter(item=>item.uid!==profile.uid&&(item.uid.toLocaleLowerCase().includes(term)||item.displayName.toLocaleLowerCase('vi').includes(term))).slice(0,12);setResults(await Promise.all(matches.map(async item=>({...item,relation:await friendshipStatus(profile.uid,item.uid)}))))}catch{setMsg('Không thể tìm người chơi lúc này.')}finally{setSearching(false)}};
 const requestFriend=async(player:FriendSummary)=>{await act(()=>sendFriendRequest(profile,player),'Đã gửi lời mời kết bạn.');setResults(current=>current.map(item=>item.uid===player.uid?{...item,relation:'sent'}:item))};
 return <section className="friends-page ui-v2-page">
  <header className="friends-hero"><div><span>MẠNG LƯỚI THỢ MỎ</span><h1>BẠN BÈ</h1><p>Kết nối đồng đội và mời họ vào phòng trước khi cuộc đào vàng bắt đầu.</p></div><div className="friends-summary"><b>{friends.length}</b><span>BẠN BÈ</span></div></header>
  {msg&&<button className="profile-message" onClick={()=>setMsg('')}>{msg}<X/></button>}
  <section className="panel friend-search-panel"><header><Search/> TÌM BẠN</header><form onSubmit={findPlayers}><input value={searchText} onChange={e=>setSearchText(e.target.value)} maxLength={60} placeholder="Nhập tên người chơi hoặc UID..." aria-label="Tên hoặc UID người chơi"/><button className="btn btn-primary" disabled={searching}>{searching?'ĐANG TÌM...':'TÌM KIẾM'}</button></form>{results.length>0&&<div className="friend-search-results">{results.map(player=><article key={player.uid}><Link to={`/profile/${player.uid}`}><PlayerIdentity compact player={{name:player.displayName,photoURL:player.photoURL,rank:player.rank,equipped:player.equipped}}/></Link>{player.relation==='none'?<button className="btn btn-primary btn-small" onClick={()=>void requestFriend(player)}><UserPlus/> KẾT BẠN</button>:<span className="friend-relation">{player.relation==='friends'?'ĐÃ LÀ BẠN':player.relation==='sent'?'ĐÃ GỬI LỜI MỜI':'ĐÃ NHẬN LỜI MỜI'}</span>}</article>)}</div>}{searched&&!searching&&!results.length&&<div className="friend-search-empty">Không tìm thấy người chơi phù hợp.</div>}</section>
  {invites.length>0&&<section className="panel friends-section room-invite-list"><header><DoorOpen/> LỜI MỜI VÀO PHÒNG <small>{invites.length}</small></header><div>{invites.map(invite=><article key={invite.id}><PlayerIdentity player={{name:invite.fromName,photoURL:invite.fromPhotoURL}} subtitle={`Mời bạn vào ${invite.roomName}`}/><span>Mã phòng <b>{invite.roomCode}</b></span><div><Link className="btn btn-primary btn-small" to={`/room?invite=${encodeURIComponent(invite.id)}`}>THAM GIA</Link><button className="btn btn-ghost btn-small" onClick={()=>void act(()=>dismissRoomInvite(profile.uid,invite.roomId),'Đã bỏ lời mời.')}>BỎ QUA</button></div></article>)}</div></section>}
  {requests.length>0&&<section className="panel friends-section"><header><UserRound/> LỜI MỜI KẾT BẠN <small>{requests.length}</small></header><div>{requests.map(request=><article key={request.fromUid}><Link to={`/profile/${request.fromUid}`}><PlayerIdentity player={{name:request.displayName,photoURL:request.photoURL,rank:request.rank,equipped:request.equipped}}/></Link><div><button className="btn btn-primary btn-small" onClick={()=>void act(()=>acceptFriendRequest(profile,request),'Đã trở thành bạn bè.')}><Check/> CHẤP NHẬN</button><button className="btn btn-ghost btn-small" onClick={()=>void act(()=>declineFriendRequest(profile.uid,request.fromUid),'Đã từ chối lời mời.')}><X/> TỪ CHỐI</button></div></article>)}</div></section>}
  <section className="panel friends-section"><header><Users/> DANH SÁCH BẠN BÈ <small>{friends.length}</small></header>{friends.length?<div>{friends.map(friend=><article key={friend.uid}><Link to={`/profile/${friend.uid}`}><PlayerIdentity player={{name:friend.displayName,photoURL:friend.photoURL,rank:friend.rank,equipped:friend.equipped}}/></Link><button className="btn btn-danger btn-small" onClick={()=>void act(()=>removeFriend(profile.uid,friend.uid),'Đã huỷ kết bạn.')}><UserMinus/> HUỶ BẠN</button></article>)}</div>:<div className="profile-empty"><Users/><b>Chưa có bạn bè</b><span>Tìm theo tên hoặc UID để gửi lời mời kết bạn.</span></div>}</section>
 </section>;
}
