import { useEffect, useMemo, useRef, useState } from 'react';
import { Ban, Bot, Box, Clock3, Coins, DoorOpen, Expand, Gem, Hammer, HeartPulse, HelpCircle, Minimize, Mountain, Pickaxe, RefreshCcw, RotateCcw, Search, Shield, ShieldPlus, Sparkles, Trash2, Trophy, UserRound, Settings, X } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Card, discardCard, GameState, GOLD_MINE_MAP, isValidPlacement, newGame, placeCard, scoutTreasure, useAction, dirs, PathKind, SpecialKind, useBlock, useRevive, useSwap, useSabotage, placementReason } from '../lib/game';
import { botMoveWithDeckActions as botMove } from '../lib/gameBot';
import { useAuth } from '../context/AuthContext';
import { MatchReward, rollMatchReward, levelFromExp, expForLevel } from '../lib/progression';
import PlayerIdentity from '../components/PlayerIdentity';
import ChatPanel from '../components/ChatPanel';

function TunnelSvg({card,small=false}:{card:Card;small?:boolean}){
 if(card.type==='action'){
  const Icon=card.kind==='delete'?Hammer:card.kind==='shield'?ShieldPlus:card.kind==='rotate'?RotateCcw:card.kind==='block'?Ban:card.kind==='revive'?HeartPulse:card.kind==='swap'?RefreshCcw:Search;
  return <span className="action-art"><Icon aria-hidden="true"/></span>;
 }
 const open=dirs(card.kind as PathKind,card.rotation);const w=small?54:78;
 return <svg className="tunnel-svg" width={w} height={w} viewBox="0 0 100 100" aria-label={card.label}>
  <defs><radialGradient id={`rock-${card.id}`}><stop offset="0" stopColor="#5a4528"/><stop offset="1" stopColor="#21180f"/></radialGradient></defs>
  <rect x="3" y="3" width="94" height="94" rx="12" fill={`url(#rock-${card.id})`} stroke="#82652c" strokeWidth="3"/>
  {open.includes('U')&&<Tunnel x1={50} y1={0} x2={50} y2={52}/>} {open.includes('R')&&<Tunnel x1={48} y1={50} x2={100} y2={50}/>} {open.includes('D')&&<Tunnel x1={50} y1={48} x2={50} y2={100}/>} {open.includes('L')&&<Tunnel x1={0} y1={50} x2={52} y2={50}/>} 
  <circle cx="50" cy="50" r="14" fill="#17120c" stroke="#c49335" strokeWidth="3"/>
  {card.kind==='collapse'&&<g><circle cx="56" cy="50" r="10" fill="#756b5d"/><circle cx="43" cy="55" r="8" fill="#514b42"/><path d="M35 42l8 7 7-11 8 10 8-7" fill="none" stroke="#bd9b56" strokeWidth="4"/></g>}
 </svg>
}
function Tunnel({x1,y1,x2,y2}:{x1:number;y1:number;x2:number;y2:number}){return <g><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#100d09" strokeWidth="25"/><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#d09a35" strokeWidth="3" strokeDasharray="8 7"/></g>}

export default function Game(){
 const{profile,completeMatch}=useAuth();const navigate=useNavigate();const[searchParams]=useSearchParams();const gameRef=useRef<HTMLElement>(null);const logRef=useRef<HTMLDivElement>(null);
  const matchStartedAt=useRef(Date.now());const[ping,setPing]=useState<number|null>(null);const[reportTarget,setReportTarget]=useState<number|null>(null);const[reportReason,setReportReason]=useState('AFK');const[reportMessage,setReportMessage]=useState('');const[state,setState]=useState<GameState>(()=>{const roomId=searchParams.get('mode')==='room'?searchParams.get('room'):null;if(roomId){try{const saved=localStorage.getItem(`room-game:${roomId}`);if(saved)return JSON.parse(saved) as GameState}catch{}}const total=Math.min(8,Math.max(6,Number(searchParams.get('players')||6)));return newGame(profile?.displayName||'Bạn',total-1,GOLD_MINE_MAP)});const[selected,setSelected]=useState<number|null>(null);const[isFullscreen,setIsFullscreen]=useState(false);const[aiThinking,setAiThinking]=useState(false);const[showFullscreenPrompt,setShowFullscreenPrompt]=useState(()=>localStorage.getItem('goldmine-fullscreen-choice')!=='normal');const[rememberFullscreen,setRememberFullscreen]=useState(false);const[showPlayersModal,setShowPlayersModal]=useState(false);const[showLeaveConfirm,setShowLeaveConfirm]=useState(false);const[special,setSpecial]=useState<SpecialKind|null>(null);const[targetPlayer,setTargetPlayer]=useState<number|null>(null);const[mySwapCard,setMySwapCard]=useState<number|null>(null);const[sabotageMode,setSabotageMode]=useState(false);const[statsSaved,setStatsSaved]=useState(false);const[matchRewards,setMatchRewards]=useState<Record<string,MatchReward>|null>(null);

 const[roomAccess,setRoomAccess]=useState<'checking'|'allowed'|'denied'>(()=>searchParams.get('mode')==='room'?'checking':'allowed');
 const[showOrientationHint,setShowOrientationHint]=useState(()=>localStorage.getItem('goldmine-orientation-hint')!=='dismissed');
 useEffect(()=>{const roomId=searchParams.get('mode')==='room'?searchParams.get('room'):null;if(roomId)localStorage.setItem(`room-game:${roomId}`,JSON.stringify(state))},[state,searchParams]);
 useEffect(()=>{let cancelled=false;const verify=async()=>{if(searchParams.get('mode')!=='room'){setRoomAccess('allowed');return}const roomId=searchParams.get('room');if(!db||!profile||!roomId){setRoomAccess('denied');return}try{const snap=await getDoc(doc(db,'rooms',roomId));const data=snap.data() as {status?:string;players?:Array<{uid:string;bot?:boolean}>}|undefined;const member=Boolean(data?.players?.some(p=>p.uid===profile.uid));if(!cancelled)setRoomAccess(snap.exists()&&data?.status==='started'&&member?'allowed':'denied')}catch{if(!cancelled)setRoomAccess('denied')}};void verify();return()=>{cancelled=true}},[profile?.uid,searchParams]);

 const human=state.players[0],current=state.players[state.turn];
 const toggleFullscreen=async()=>{try{if(!document.fullscreenElement)await gameRef.current?.requestFullscreen();else await document.exitFullscreen()}catch{}}
 useEffect(()=>{const measure=async()=>{const start=performance.now();try{await fetch('/',{method:'HEAD',cache:'no-store'});setPing(Math.round(performance.now()-start))}catch{setPing(null)}};void measure();const t=window.setInterval(()=>void measure(),10000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{const onChange=()=>setIsFullscreen(Boolean(document.fullscreenElement));const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&showLeaveConfirm){setShowLeaveConfirm(false);return}if(e.key.toLowerCase()==='f'&&!e.repeat){e.preventDefault();void toggleFullscreen()}};document.addEventListener('fullscreenchange',onChange);window.addEventListener('keydown',onKey);return()=>{document.removeEventListener('fullscreenchange',onChange);window.removeEventListener('keydown',onKey)}},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setShowLeaveConfirm(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
  useEffect(()=>{if(current?.isBot&&!state.winner){setAiThinking(true);const delay=2500+Math.random()*1000;const t=setTimeout(()=>{setState(s=>botMove(s));setAiThinking(false)},delay);return()=>{clearTimeout(t);setAiThinking(false)}}},[state.turn,state.winner]);
  useEffect(()=>{if(!state.winner||matchRewards)return;const rewards:Record<string,MatchReward>={};for(const player of state.players){const won=state.winner===(player.role==='miner'?'miners':'wolves');rewards[player.id]=rollMatchReward(won,player.score)}setMatchRewards(rewards)},[state.winner,state.matchId,matchRewards]);
  useEffect(()=>{if(!state.winner||!matchRewards||statsSaved)return;const reward=matchRewards[human.id];if(!reward)return;setStatsSaved(true);void completeMatch(state.winner===(human.role==='miner'?'miners':'wolves'),state.matchId,reward,{role:human.role,turns:state.logs.length,durationSeconds:Math.floor((Date.now()-matchStartedAt.current)/1000),opponents:state.players.slice(1).map(p=>p.name)})},[state.winner,statsSaved,state.matchId,matchRewards,human.id,human.role,completeMatch]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const el=logRef.current;if(!el)return;el.scrollTop=0;});return()=>cancelAnimationFrame(frame)},[state.logs]);
 const chooseFullscreen=async(full:boolean)=>{if(rememberFullscreen)localStorage.setItem('goldmine-fullscreen-choice',full?'fullscreen':'normal');setShowFullscreenPrompt(false);if(full)await toggleFullscreen()};
 const dismissOrientationHint=()=>{localStorage.setItem('goldmine-orientation-hint','dismissed');setShowOrientationHint(false)};
  const playable=state.turn===0&&!state.winner&&!aiThinking;const selectedCard=selected===null?null:human.hand[selected];
 const select=(i:number)=>{if(!playable)return;setSabotageMode(false);const card=human.hand[i];if(card?.kind==='block'||card?.kind==='revive'||card?.kind==='swap'){setSelected(i);setSpecial(card.kind);setTargetPlayer(null);setMySwapCard(null);return}setSelected(selected===i?null:i)};
 const discardSelected=()=>{if(!playable||selected===null)return;const next=discardCard(state,0,selected);if(next!==state){setState(next);setSelected(null)}};
  const clickCell=(r:number,c:number)=>{if(!playable)return;if(sabotageMode){const next=useSabotage(state,0,r,c);if(next!==state){setState(next);setSabotageMode(false)}return}if(selected===null)return;const next=selectedCard?.type==='path'?placeCard(state,0,selected,r,c):useAction(state,0,selected,r,c);if(next!==state){setState(next);setSelected(null)}};
 const useSpecialTarget=(target:number)=>{if(!special||!playable||selected===null)return;if(special==='block'){const next=useBlock(state,0,target,selected);if(next!==state){setState(next);setSelected(null);setSpecial(null)}}else if(special==='revive'){const next=useRevive(state,0,target,selected);if(next!==state){setState(next);setSelected(null);setSpecial(null)}}else setTargetPlayer(target)};
 const finishSwap=(targetCard:number)=>{if(targetPlayer===null||mySwapCard===null||selected===null)return;const next=useSwap(state,0,mySwapCard,targetPlayer,targetCard,selected);if(next!==state){setState(next);setSelected(null);setSpecial(null);setTargetPlayer(null);setMySwapCard(null)}};
 const clickTreasure=(id:string)=>{if(!playable||selected===null||selectedCard?.kind!=='scout')return;const next=scoutTreasure(state,0,selected,id);if(next!==state){setState(next);setSelected(null)}};
 const leaveTable=async()=>{if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});const roomId=searchParams.get('mode')==='room'?searchParams.get('room'):null;if(roomId){localStorage.removeItem(`room-game:${roomId}`);if(profile)localStorage.removeItem(`active-room:${profile.uid}`)}navigate('/room')};
 const roleText=human.role==='miner'?'THỢ ĐÀO':'SÓI';
 const playerExp=Math.max(0,profile?.exp||0);const playerLevel=levelFromExp(playerExp);const levelStart=expForLevel(playerLevel);const levelEnd=expForLevel(playerLevel+1);const levelProgress=Math.min(100,Math.max(0,((playerExp-levelStart)/Math.max(1,levelEnd-levelStart))*100));
 if(roomAccess==='checking')return <section className="center-page"><div className="auth-card"><Pickaxe className="spin-slow"/><h1>ĐANG XÁC MINH PHÒNG</h1></div></section>;
 if(roomAccess==='denied')return <section className="center-page"><div className="auth-card"><Shield/><h1>KHÔNG THỂ VÀO TRẬN</h1><p>Phòng không hợp lệ, chưa bắt đầu hoặc bạn không thuộc phòng này.</p><button className="btn btn-primary" onClick={()=>navigate('/room',{replace:true})}>VỀ PHÒNG CHỜ</button></div></section>;
 return <section className={`game-page ${profile?.equipped.boardSkin||'board-default'} ${profile?.equipped.pieceSkin||'piece-default'}`} ref={gameRef}>
  {showOrientationHint&&<div className="orientation-hint"><div className="orientation-hint-card"><span className="orientation-phone"><RotateCcw aria-hidden="true"/></span><span className="eyebrow">TRẢI NGHIỆM MOBILE</span><h2>XOAY NGANG ĐỂ CHƠI TỐT HƠN</h2><p>Bàn cờ và bộ bài sẽ rộng, dễ quan sát và thao tác hơn khi điện thoại nằm ngang.</p><button className="btn btn-primary btn-wide" onClick={dismissOrientationHint}>ĐÃ HIỂU</button></div></div>}
  {showFullscreenPrompt&&<div className="fullscreen-prompt"><div className="fullscreen-card"><button className="prompt-close" onClick={()=>setShowFullscreenPrompt(false)}><X/></button><span className="eyebrow">CHẾ ĐỘ TRẬN ĐẤU</span><h2>SẴN SÀNG ĐÀO VÀNG?</h2><p>Khuyến nghị bật toàn màn hình để thấy trọn bàn cờ và bảng điều khiển.</p><button className="btn btn-primary btn-wide" onClick={()=>void chooseFullscreen(true)}><Expand/> BẬT TOÀN MÀN HÌNH</button><button className="btn btn-ghost btn-wide" onClick={()=>void chooseFullscreen(false)}>CHƠI BÌNH THƯỜNG</button><label><input type="checkbox" checked={rememberFullscreen} onChange={e=>setRememberFullscreen(e.target.checked)}/> Ghi nhớ lựa chọn</label><small>Nhấn <b>F</b> để bật/tắt fullscreen.</small></div></div>}
   <div className="game-top"><div><span>{`MAP: ${state.map.id.toUpperCase()}`}</span><h1>{state.map.name}</h1></div><div className="hud-status"><div className="turn-pill"><Clock3/> {state.winner?'TRẬN ĐÃ KẾT THÚC':aiThinking?`${current.name} ĐANG SUY NGHĨ...`:current?.isBot?`${current.name} ĐANG ĐI`:'ĐẾN LƯỢT BẠN'}</div></div><div className="game-actions"><span className={`ping-badge ${ping===null?'offline':ping<100?'good':ping<220?'medium':'bad'}`} title="Độ trễ mạng"><b>{ping===null?'--':ping}</b><small>ms</small></span><button aria-label="Cài đặt" title="Cài đặt" className="btn btn-ghost btn-small action-settings" onClick={()=>setShowPlayersModal(true)}><Settings/><span>Cài đặt</span></button><button aria-label={isFullscreen?'Thu nhỏ':'Toàn màn hình'} title={isFullscreen?'Thu nhỏ':'Toàn màn hình'} className="btn btn-ghost btn-small action-fullscreen" onClick={()=>void toggleFullscreen()}>{isFullscreen?<Minimize/>:<Expand/>}<span>{isFullscreen?'Thu nhỏ':'Toàn màn hình'}</span></button><button aria-label="Rời bàn" title="Rời bàn" className="btn btn-danger btn-small action-leave" onClick={()=>setShowLeaveConfirm(true)}><DoorOpen/><span>Rời bàn</span></button></div></div>
  <div className="game-layout-v5">
    <main className="board-wrap">
      <div className="mine-board-shell dynamic">
        <div className="mine-entrance" aria-label="Cửa hầm"><span><Pickaxe aria-hidden="true"/></span><b>CỬA HẦM</b><i/></div>
        <div className="board dynamic-board" style={{gridTemplateColumns:`repeat(${state.map.cols},1fr)`,gridTemplateRows:`repeat(${state.map.rows},1fr)`}}>{state.board.map((row,r)=>row.map((cell,c)=>{const legal=playable&&human.blockedTurns<=0&&selectedCard?.type==='path'&&!cell&&isValidPlacement(state.board,selectedCard,r,c,state.map,state.obstacles);const obstacle=state.obstacles.includes(`${r},${c}`);return <button disabled={obstacle} onClick={()=>clickCell(r,c)} key={`${r}-${c}`} className={`cell ${cell?'occupied':''} ${legal?'legal':''} ${obstacle?'obstacle':''}`}><span className="grid-coord">{String.fromCharCode(65+c)}{r+1}</span>{obstacle?<div className="obstacle-art cliff"><Mountain aria-hidden="true"/><b>VÁCH ĐÁ</b></div>:cell&&<TunnelSvg card={cell.card} small/>}{cell?.shield&&<Shield className="shield-mark"/>}</button>}))}</div>
        <div className="treasure-column compact" style={{gridTemplateRows:`repeat(${state.map.rows},1fr)`}}>{state.map.objectives.map(o=>{const t=state.treasures.find(x=>x.id===o.id)!;const peek=t.peekedBy.includes(human.id);return <button onClick={()=>clickTreasure(o.id)} key={o.id} className={`treasure-slot ${t.revealed?'revealed':''} ${t.revealed&&t.isGold?'gold':''} ${peek?'peeked':''} ${peek?(t.isGold?'peeked-gold':'peeked-fake'):''}`} style={{gridRow:(o.row??0)+1}} title={t.revealed?(t.isGold?'Kho báu thật':'Rương giả'):peek?(t.isGold?'Bạn đã thăm dò: KHO BÁU THẬT':'Bạn đã thăm dò: RƯƠNG GIẢ'):'Rương bí ẩn'}><span>{peek||t.revealed?(t.isGold?<Gem aria-hidden="true"/>:<Mountain aria-hidden="true"/>):<Box aria-hidden="true"/>}</span>{peek&&!t.revealed&&<b>{t.isGold?'THẬT':'GIẢ'}</b>}</button>})}</div>
      </div>
      <div className="board-help">Bàn {state.map.cols}×{state.map.rows} · Không thể đặt hoặc phá đường trên ô đá.</div>
    </main>
    <aside className="battle-right-column">
      <section className="battle-journal panel" ref={logRef}>
        <ChatPanel compact systemMessages={state.logs.slice(0,20)} roomId={searchParams.get('room')||`match-${state.matchId}`}/>
      </section>
    </aside>
  </div>
  <footer className="game-bottom-hud redesigned-bottom-hud">
    <div className="player-hand-row">
    <section className="player-progress-card">
      <div className="progress-avatar-wrap"><span className="progress-avatar">{profile?.photoURL?<img src={profile.photoURL} alt=""/>:<UserRound/>}</span><i className="online-dot"/></div>
      <div className="progress-player-copy"><div className="progress-name-line"><b>{human.name}</b><span><Sparkles/> LV. {playerLevel}</span></div><strong className={human.role}>{roleText}</strong><div className="exp-values"><small>{playerExp.toLocaleString('vi-VN')} / {levelEnd.toLocaleString('vi-VN')}</small></div><div className="exp-track"><i style={{width:`${levelProgress}%`}}/></div></div>
    </section>
    <section className={`hand-hud-panel ${!playable?'is-waiting':''}`}><header><b>HƯỚNG ĐI</b><small>{sabotageMode?'Chọn đường cần phá':selected===null?'Chọn một lá để sử dụng':human.hand[selected]?.label}</small></header><div className="hand-hud-cards">{human.hand.map((card,i)=><button data-slot={i+1} onClick={()=>select(i)} className={`hand-hud-card ${card.type} ${card.kind} ${human.blockedTurns>0&&card.type==='path'?'movement-locked':''} ${selected===i?'selected':''}`} key={card.id} title={human.blockedTurns>0&&card.type==='path'?'Đang bị Chặn: chỉ có thể bỏ lá này':card.label}><span><TunnelSvg card={card}/></span><b>{card.label}</b><small>{card.type==='path'?'ĐƯỜNG':'CHỨC NĂNG'}</small></button>)}</div><button className="hand-hud-discard" disabled={!playable||selected===null} onClick={discardSelected}><Trash2/><span>BỎ THẺ</span></button>
    {human.canSabotage&&<section className="bottom-special-hand wolf-only-skill">
      <header><span>KỸ NĂNG SÓI</span><small>Kỹ năng bí mật dùng một lần</small></header>
      <div className="bottom-special-grid"><button className={`bottom-special-card sabotage ${sabotageMode?'selected':''}`} disabled={!playable||human.sabotageUsed} onClick={()=>{setSelected(null);setSabotageMode(v=>!v)}}><Hammer/><span><em>KỸ NĂNG SÓI</em><b>PHÁ SẬP HẦM</b><small>Phá tâm và 4 mảnh kề · dùng 1 lần</small></span></button></div>
    </section>}
    </section>
    </div>
  </footer>

  {state.winner&&matchRewards&&<div className="match-summary-modal"><div className="match-summary-card"><header><div><span className="eyebrow">TỔNG KẾT TRẬN ĐẤU</span><h2>{state.winner==='miners'?'THỢ ĐÀO CHIẾN THẮNG':'SÓI CHIẾN THẮNG'}</h2><p>Vai trò đã được công khai. Vàng và EXP chỉ được cộng sau khi trận hoàn tất.</p></div><Trophy aria-hidden="true"/></header><div className="match-summary-table"><div className="summary-head"><span>NGƯỜI CHƠI</span><span>VAI TRÒ</span><span>KẾT QUẢ</span><span>VÀNG</span><span>EXP</span></div>{state.players.map((p,i)=>{const won=state.winner===(p.role==='miner'?'miners':'wolves');const reward=matchRewards[p.id];return <div className={`summary-row ${i===0?'is-you':''} ${won?'is-winner':''}`} key={p.id}><span className="summary-player"><i>{p.isBot?<Bot aria-hidden="true"/>:<UserRound aria-hidden="true"/>}</i><b>{p.name}{i===0?' (Bạn)':''}</b></span><span><strong className={`role-chip ${p.role}`}>{p.role==='miner'?'THỢ ĐÀO':p.canSabotage?'SÓI PHÁ HẦM':'SÓI'}</strong></span><span><strong className={won?'result-win':'result-loss'}>{won?'THẮNG':'THUA'}</strong></span><span className="reward-value coins"><Coins/> +{reward.coins}</span><span className="reward-value exp"><Sparkles/> +{reward.exp}</span></div>})}</div><footer><div className="your-reward"><small>PHẦN THƯỞNG CỦA BẠN</small><b><Coins/> +{matchRewards[human.id].coins} vàng</b><b><Sparkles/> +{matchRewards[human.id].exp} EXP</b><span>{statsSaved?'Đã ghi nhận vào hồ sơ.':'Đang ghi nhận phần thưởng...'}</span></div><button className="btn btn-primary" onClick={()=>void leaveTable()}>HOÀN TẤT & RỜI BÀN</button></footer></div></div>}

  {special&&<div className="leave-modal special-modal" onMouseDown={e=>{if(e.target===e.currentTarget){setSpecial(null);setTargetPlayer(null);setMySwapCard(null)}}}><div className={`leave-card special-card skill-${special}`}><button className="prompt-close" onClick={()=>{setSpecial(null);setTargetPlayer(null);setMySwapCard(null)}}><X/></button><div className="special-hero-icon">{special==='block'?<Ban aria-hidden="true"/>:special==='revive'?<HeartPulse aria-hidden="true"/>:<RefreshCcw aria-hidden="true"/>}</div><span className="eyebrow">LÁ ĐẶC BIỆT</span><h2>{special==='block'?'CHẶN ĐƯỜNG':special==='revive'?'HỒI SINH':'ĐỔI BÀI ÚP'}</h2>{special==='swap'&&mySwapCard===null?<><p>Chọn một lá bài của bạn để mang đi đổi.</p><div className="swap-my-cards">{human.hand.map((c,i)=><button key={c.id} onClick={()=>setMySwapCard(i)}><TunnelSvg card={c} small/><b>{c.label}</b></button>)}</div></>:targetPlayer===null?<><p>{special==='revive'?'Chọn chính bạn hoặc một người khác đang bị Chặn.':special==='swap'?'Chọn người chơi bạn muốn đổi bài.':'Chọn người chơi mục tiêu.'}</p><div className="special-player-list">{state.players.map((p,i)=>special==='block'&&i===0?null:<button disabled={(special==='revive'&&p.blockedTurns<=0)||(special==='block'&&p.blockedTurns>0)} key={p.id} onClick={()=>useSpecialTarget(i)}><span>{i===0?<UserRound aria-hidden="true"/>:p.isBot?<Bot aria-hidden="true"/>:<UserRound aria-hidden="true"/>}</span><b>{p.name}{i===0?' (Bạn)':''}</b><small>{p.blockedTurns>0?'ĐANG BỊ CHẶN':`${p.hand.length} lá úp`}</small></button>)}</div></>:<><p>Chọn một lá đang úp của {state.players[targetPlayer].name}. Bạn chỉ biết lá gì sau khi đổi.</p><div className="facedown-cards">{state.players[targetPlayer].hand.map((_,i)=><button key={i} onClick={()=>finishSwap(i)}><span><Box aria-hidden="true"/></span><b>LÁ {i+1}</b></button>)}</div></>}</div></div>}

  {showPlayersModal&&<div className="leave-modal players-settings-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setShowPlayersModal(false)}}><div className="leave-card players-settings-card"><button className="prompt-close" onClick={()=>setShowPlayersModal(false)}><X/></button><div className="settings-modal-head"><Settings/><div><span className="eyebrow">CÀI ĐẶT TRẬN ĐẤU</span><h2>NGƯỜI CHƠI</h2></div></div><div className="settings-player-list">{state.players.map((p,i)=><div className={`player-row ${state.turn===i?'active':''}`} key={p.id}><PlayerIdentity compact active={state.turn===i} player={{name:i===0?`${p.name} - ${roleText}`:p.name,bot:p.isBot,photoURL:i===0?profile?.photoURL:'',rank:i===0?profile?.rank:undefined,equipped:i===0?profile?.equipped:undefined}} hideSubtitle/>{i>0&&!p.isBot&&<button className="report-mini" onClick={()=>setReportTarget(i)}>BÁO CÁO</button>}</div>)}</div><button className="btn btn-primary btn-wide" onClick={()=>setShowPlayersModal(false)}>ĐÓNG</button></div></div>}
  {reportTarget!==null&&<div className="leave-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setReportTarget(null)}}><div className="leave-card report-card"><button className="prompt-close" onClick={()=>setReportTarget(null)}><X/></button><Shield/><span className="eyebrow">BÁO CÁO NGƯỜI CHƠI</span><h2>{state.players[reportTarget]?.name}</h2><select value={reportReason} onChange={e=>setReportReason(e.target.value)}><option>AFK</option><option>Spam</option><option>Tên phản cảm</option><option>Phá game</option><option>Nghi gian lận</option></select><button className="btn btn-danger btn-wide" onClick={async()=>{if(!db||!profile||reportTarget===null)return;const target=state.players[reportTarget];const id=`${state.matchId}_${profile.uid}_${target.id}`;try{await setDoc(doc(db,'reports',id),{matchId:state.matchId,reporterUid:profile.uid,targetId:target.id,targetName:target.name,reason:reportReason,createdAt:serverTimestamp()});setReportMessage('Đã gửi báo cáo.');setReportTarget(null)}catch(e:any){setReportMessage(e?.message||'Không thể gửi báo cáo.')}}}>GỬI BÁO CÁO</button></div></div>}
  {reportMessage&&<div className="game-toast" onClick={()=>setReportMessage('')}>{reportMessage}</div>}
  {showLeaveConfirm&&<div className="leave-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setShowLeaveConfirm(false)}}><div className="leave-card"><DoorOpen/><span className="eyebrow">XÁC NHẬN</span><h2>RỜI BÀN?</h2><p>Bạn có chắc muốn rời trận? Tiến trình hiện tại sẽ không được giữ lại.</p><div><button className="btn btn-ghost" onClick={()=>setShowLeaveConfirm(false)}>Ở LẠI</button><button className="btn btn-danger" onClick={()=>void leaveTable()}>RỜI BÀN</button></div></div></div>}
 </section>
}
