import { useEffect, useMemo, useRef, useState } from 'react';
import { Ban, Bot, Box, Clock3, Coins, DoorOpen, Expand, Gem, Hammer, HeartPulse, HelpCircle, MessageCircle, Minimize, Mountain, Pickaxe, RefreshCcw, RotateCcw, Search, Shield, Sparkles, Trash2, Trophy, UserRound, Settings, X } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { doc, getDoc, onSnapshot, runTransaction, serverTimestamp, setDoc } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Card, discardCard, GameState, GOLD_MINE_MAP, isValidPlacement, newGame, placeCard, scoutTreasure, useAction, dirs, isDeadPath, PathKind, SpecialKind, useBlock, useRevive, useSwap, useSabotage, placementReason } from '../lib/game';
import { botMoveWithDeckActions as botMove } from '../lib/gameBot';
import { useAuth } from '../context/AuthContext';
import { MatchReward, rollMatchReward, levelFromExp, expForLevel } from '../lib/progression';
import PlayerIdentity from '../components/PlayerIdentity';
import ChatPanel from '../components/ChatPanel';
import { applyPresenceRules, decodeOnlineMatch, encodeOnlineMatch, OnlineMatch, OnlineMatchDocument, timeoutTurn, TURN_MS } from '../lib/onlineMatch';

function TunnelSvg({card,small=false}:{card:Card;small?:boolean}){
 if(card.type==='action'){
  const Icon=card.kind==='delete'?Hammer:card.kind==='rotate'?RotateCcw:card.kind==='block'?Ban:card.kind==='revive'?HeartPulse:card.kind==='swap'?RefreshCcw:Search;
  return <span className="action-art"><Icon aria-hidden="true"/></span>;
 }
 const kind=card.kind as PathKind;const open=dirs(kind,card.rotation);const dead=isDeadPath(kind);const cornerDead=kind==='nwDead'||kind==='seDead'||kind==='swDead';const deadArm=kind==='nwDead'?'R':kind==='seDead'?'L':kind==='swDead'?'R':null;const w=small?54:78;
 return <svg className="tunnel-svg" width={w} height={w} viewBox="0 0 100 100" aria-label={card.label}>
  <defs><radialGradient id={`rock-${card.id}`}><stop offset="0" stopColor="#5a4528"/><stop offset="1" stopColor="#21180f"/></radialGradient></defs>
  <rect x="3" y="3" width="94" height="94" rx="12" fill={`url(#rock-${card.id})`} stroke="#82652c" strokeWidth="3"/>
  {open.includes('U')&&<Tunnel x1={50} y1={0} x2={50} y2={cornerDead?52:dead?34:52} dead={dead&&!cornerDead}/>} {open.includes('R')&&<Tunnel x1={dead?66:48} y1={50} x2={100} y2={50} dead={dead}/>} {open.includes('D')&&<Tunnel x1={50} y1={cornerDead?48:dead?66:48} x2={50} y2={100} dead={dead&&!cornerDead}/>} {open.includes('L')&&<Tunnel x1={0} y1={50} x2={dead?34:52} y2={50} dead={dead}/>}
  {deadArm==='R'&&<Tunnel x1={48} y1={50} x2={72} y2={50} dead/>}
  {deadArm==='L'&&<Tunnel x1={52} y1={50} x2={28} y2={50} dead/>}
  {!dead&&<circle cx="50" cy="50" r="14" fill="#17120c" stroke="#c49335" strokeWidth="3"/>}
  {dead&&card.kind!=='collapse'&&<circle cx="50" cy="50" r="9" fill="#30251a" stroke="#82652c" strokeWidth="2" strokeDasharray="3 3"/>}
  {card.kind==='collapse'&&<g><circle cx="56" cy="50" r="10" fill="#756b5d"/><circle cx="43" cy="55" r="8" fill="#514b42"/><path d="M35 42l8 7 7-11 8 10 8-7" fill="none" stroke="#bd9b56" strokeWidth="4"/></g>}
 </svg>
}
function Tunnel({x1,y1,x2,y2,dead=false}:{x1:number;y1:number;x2:number;y2:number;dead?:boolean}){return <g><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#100d09" strokeWidth="25"/><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#d09a35" strokeWidth="3" strokeDasharray="8 7"/>{dead&&<circle cx={x2===0||x2===100?x1:x2} cy={y2===0||y2===100?y1:y2} r="5" fill="#17120c" stroke="#b48633" strokeWidth="2"/>}</g>}

export default function Game(){
 const{profile,completeMatch}=useAuth();const navigate=useNavigate();const[searchParams]=useSearchParams();const gameRef=useRef<HTMLElement>(null);const logRef=useRef<HTMLDivElement>(null);
  const matchStartedAt=useRef(Date.now());const[ping,setPing]=useState<number|null>(null);const[reportTarget,setReportTarget]=useState<number|null>(null);const[reportReason,setReportReason]=useState('AFK');const[reportMessage,setReportMessage]=useState('');const[state,setState]=useState<GameState>(()=>{const roomId=searchParams.get('mode')==='room'?searchParams.get('room'):null;if(roomId){try{const saved=localStorage.getItem(`room-game:${roomId}`);if(saved)return JSON.parse(saved) as GameState}catch{}}const total=Math.min(8,Math.max(6,Number(searchParams.get('players')||6)));return newGame(profile?.displayName||'Bạn',total-1,GOLD_MINE_MAP)});const[selected,setSelected]=useState<number|null>(null);const[isFullscreen,setIsFullscreen]=useState(false);const[aiThinking,setAiThinking]=useState(false);const[showFullscreenPrompt,setShowFullscreenPrompt]=useState(()=>localStorage.getItem('goldmine-fullscreen-choice')!=='normal');const[rememberFullscreen,setRememberFullscreen]=useState(false);const[showPlayersModal,setShowPlayersModal]=useState(false);const[showLeaveConfirm,setShowLeaveConfirm]=useState(false);const[special,setSpecial]=useState<SpecialKind|null>(null);const[targetPlayer,setTargetPlayer]=useState<number|null>(null);const[mySwapCard,setMySwapCard]=useState<number|null>(null);const[sabotageMode,setSabotageMode]=useState(false);const[statsSaved,setStatsSaved]=useState(false);const[matchRewards,setMatchRewards]=useState<Record<string,MatchReward>|null>(null);

 const[roomAccess,setRoomAccess]=useState<'checking'|'allowed'|'denied'>(()=>searchParams.get('mode')==='room'?'checking':'allowed');
 const[onlineMatch,setOnlineMatch]=useState<OnlineMatch|null>(null);
 const[mobileChatOpen,setMobileChatOpen]=useState(false);
 const[mobilePlayerMenuOpen,setMobilePlayerMenuOpen]=useState(false);
 const[chatFabPosition,setChatFabPosition]=useState<{x:number;y:number}|null>(null);
 const chatFabDrag=useRef<{pointerId:number;offsetX:number;offsetY:number;startX:number;startY:number;moved:boolean}|null>(null);
 const onlineRoomId=searchParams.get('mode')==='room'?searchParams.get('room'):null;
 useEffect(()=>{if(onlineRoomId)localStorage.setItem(`room-game:${onlineRoomId}`,JSON.stringify(state))},[state,onlineRoomId]);
 useEffect(()=>{let cancelled=false;const verify=async()=>{if(searchParams.get('mode')!=='room'){setRoomAccess('allowed');return}const roomId=searchParams.get('room');if(!db||!profile||!roomId){setRoomAccess('denied');return}try{const snap=await getDoc(doc(db,'rooms',roomId));const data=snap.data() as {status?:string;players?:Array<{uid:string;bot?:boolean}>}|undefined;const member=Boolean(data?.players?.some(p=>p.uid===profile.uid));if(!cancelled)setRoomAccess(snap.exists()&&data?.status==='started'&&member?'allowed':'denied')}catch{if(!cancelled)setRoomAccess('denied')}};void verify();return()=>{cancelled=true}},[profile?.uid,searchParams]);
 useEffect(()=>{if(!db||!profile||!onlineRoomId||roomAccess!=='allowed')return;const ref=doc(db,'matches',onlineRoomId);return onSnapshot(ref,snap=>{if(!snap.exists()){setRoomAccess('denied');return}const match=decodeOnlineMatch(snap.data() as OnlineMatchDocument);setOnlineMatch(match);setState(match.state)})},[profile?.uid,onlineRoomId,roomAccess]);
 useEffect(()=>{if(!db||!profile||!onlineRoomId||!onlineMatch)return;const beat=async()=>{const ref=doc(db!,'matches',onlineRoomId);await runTransaction(db!,async tx=>{const snap=await tx.get(ref);if(!snap.exists())return;const match=decodeOnlineMatch(snap.data() as OnlineMatchDocument);if(!match.participantIds.includes(profile.uid)||match.presence[profile.uid]?.status==='left')return;const now=Date.now();match.presence[profile.uid]={status:'online',lastSeen:now,disconnectDeadline:null};tx.update(ref,{presence:match.presence})}).catch(()=>{})};void beat();const timer=window.setInterval(()=>void beat(),5000);return()=>window.clearInterval(timer)},[profile?.uid,onlineRoomId,Boolean(onlineMatch)]);
 useEffect(()=>{if(!db||!onlineRoomId||!onlineMatch?.state||onlineMatch.state.winner)return;const timer=window.setInterval(()=>{const now=Date.now();const stale=Object.values(onlineMatch.presence).some(p=>p.status==='online'&&now-p.lastSeen>12000||p.status==='disconnected'&&p.disconnectDeadline!==null&&now>=p.disconnectDeadline);if(now<onlineMatch.turnDeadline&&!stale)return;const ref=doc(db!,'matches',onlineRoomId);void runTransaction(db!,async tx=>{const snap=await tx.get(ref);if(!snap.exists())return;const current=decodeOnlineMatch(snap.data() as OnlineMatchDocument);const next=timeoutTurn(current,Date.now());if(next.revision===current.revision&&next.state.winner===current.state.winner&&next.state.turn===current.state.turn&&JSON.stringify(next.presence)===JSON.stringify(current.presence))return;tx.set(ref,encodeOnlineMatch(next))}).catch(()=>{})},1000);return()=>window.clearInterval(timer)},[onlineRoomId,onlineMatch?.turnDeadline,onlineMatch?.revision,onlineMatch?.state.winner,onlineMatch?.presence]);

 const humanIndex=onlineRoomId&&profile?Math.max(0,state.players.findIndex(player=>player.id===profile.uid)):0;
 const human=state.players[humanIndex]||state.players[0],current=state.players[state.turn];
 const commitGameState=async(transform:(current:GameState)=>GameState)=>{
  if(!onlineRoomId||!db){setState(currentState=>transform(currentState));return}
  const ref=doc(db,'matches',onlineRoomId);
  await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())return;const match=decodeOnlineMatch(snap.data() as OnlineMatchDocument);const nextState=transform(match.state);if(nextState===match.state)return;const now=Date.now();const next=applyPresenceRules({...match,state:nextState,turnStartedAt:now,turnDeadline:now+TURN_MS,revision:match.revision+1},now);tx.set(ref,encodeOnlineMatch(next))}).catch(()=>{});
 };
 const toggleFullscreen=async()=>{try{if(!document.fullscreenElement)await gameRef.current?.requestFullscreen();else await document.exitFullscreen()}catch{}}
 useEffect(()=>{const measure=async()=>{const start=performance.now();try{await fetch('/',{method:'HEAD',cache:'no-store'});setPing(Math.round(performance.now()-start))}catch{setPing(null)}};void measure();const t=window.setInterval(()=>void measure(),10000);return()=>window.clearInterval(t)},[]);
 useEffect(()=>{const onChange=()=>setIsFullscreen(Boolean(document.fullscreenElement));const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'&&showLeaveConfirm){setShowLeaveConfirm(false);return}if(e.key.toLowerCase()==='f'&&!e.repeat){e.preventDefault();void toggleFullscreen()}};document.addEventListener('fullscreenchange',onChange);window.addEventListener('keydown',onKey);return()=>{document.removeEventListener('fullscreenchange',onChange);window.removeEventListener('keydown',onKey)}},[]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setShowLeaveConfirm(false)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[]);
  useEffect(()=>{if(current?.isBot&&!state.winner){setAiThinking(true);const expectedTurn=state.turn;const delay=2500+Math.random()*1000;const t=setTimeout(()=>{void commitGameState(s=>s.turn===expectedTurn&&s.players[s.turn]?.isBot?botMove(s):s);setAiThinking(false)},delay);return()=>{clearTimeout(t);setAiThinking(false)}}},[state.turn,state.winner,current?.isBot]);
  useEffect(()=>{if(!state.winner||matchRewards)return;const rewards:Record<string,MatchReward>={};for(const player of state.players){const won=state.winner===(player.role==='miner'?'miners':'wolves');rewards[player.id]=rollMatchReward(won,player.score)}setMatchRewards(rewards)},[state.winner,state.matchId,matchRewards]);
  useEffect(()=>{if(!state.winner||!matchRewards||statsSaved)return;const reward=matchRewards[human.id];if(!reward)return;setStatsSaved(true);void completeMatch(state.winner===(human.role==='miner'?'miners':'wolves'),state.matchId,reward,{role:human.role,turns:state.logs.length,durationSeconds:Math.floor((Date.now()-matchStartedAt.current)/1000),opponents:state.players.filter(p=>p.id!==human.id).map(p=>p.name)})},[state.winner,statsSaved,state.matchId,matchRewards,human.id,human.role,completeMatch]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const el=logRef.current;if(!el)return;el.scrollTop=0;});return()=>cancelAnimationFrame(frame)},[state.logs]);
 const chooseFullscreen=async(full:boolean)=>{if(rememberFullscreen)localStorage.setItem('goldmine-fullscreen-choice',full?'fullscreen':'normal');setShowFullscreenPrompt(false);if(full)await toggleFullscreen()};
  const playable=state.turn===humanIndex&&!state.winner&&!aiThinking;const selectedCard=selected===null?null:human.hand[selected];
 const select=(i:number)=>{if(!playable)return;setSabotageMode(false);const card=human.hand[i];if(card?.kind==='block'||card?.kind==='revive'||card?.kind==='swap'){setSelected(i);setSpecial(card.kind);setTargetPlayer(null);setMySwapCard(null);return}setSelected(selected===i?null:i)};
 const discardSelected=()=>{if(!playable||selected===null)return;void commitGameState(s=>discardCard(s,humanIndex,selected));setSelected(null)};
  const clickCell=(r:number,c:number)=>{if(!playable)return;if(sabotageMode){void commitGameState(s=>useSabotage(s,humanIndex,r,c));setSabotageMode(false);return}if(selected===null)return;void commitGameState(s=>selectedCard?.type==='path'?placeCard(s,humanIndex,selected,r,c):useAction(s,humanIndex,selected,r,c));setSelected(null)};
 const useSpecialTarget=(target:number)=>{if(!special||!playable||selected===null)return;if(special==='block'){void commitGameState(s=>useBlock(s,humanIndex,target,selected));setSelected(null);setSpecial(null)}else if(special==='revive'){void commitGameState(s=>useRevive(s,humanIndex,target,selected));setSelected(null);setSpecial(null)}else setTargetPlayer(target)};
 const finishSwap=(targetCard:number)=>{if(targetPlayer===null||mySwapCard===null||selected===null)return;void commitGameState(s=>useSwap(s,humanIndex,mySwapCard,targetPlayer,targetCard,selected));setSelected(null);setSpecial(null);setTargetPlayer(null);setMySwapCard(null)};
 const clickTreasure=(id:string)=>{if(!playable||selected===null||selectedCard?.kind!=='scout')return;void commitGameState(s=>scoutTreasure(s,humanIndex,selected,id));setSelected(null)};
 const leaveTable=async()=>{if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});if(onlineRoomId&&db&&profile){const ref=doc(db,'matches',onlineRoomId);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(!snap.exists())return;const match=decodeOnlineMatch(snap.data() as OnlineMatchDocument);const presence=match.presence[profile.uid];if(!presence)return;match.presence[profile.uid]={...presence,status:'left',disconnectDeadline:null,lastSeen:Date.now()};const next=applyPresenceRules(match,Date.now());tx.set(ref,encodeOnlineMatch({...next,revision:next.revision+1}))}).catch(()=>{});localStorage.removeItem(`room-game:${onlineRoomId}`);localStorage.removeItem(`active-room:${profile.uid}`)}navigate('/room')};
 const startChatFabDrag=(e:React.PointerEvent<HTMLButtonElement>)=>{const rect=e.currentTarget.getBoundingClientRect();chatFabDrag.current={pointerId:e.pointerId,offsetX:e.clientX-rect.left,offsetY:e.clientY-rect.top,startX:e.clientX,startY:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId)};
 const moveChatFab=(e:React.PointerEvent<HTMLButtonElement>)=>{const drag=chatFabDrag.current;if(!drag||drag.pointerId!==e.pointerId)return;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5)drag.moved=true;const size=48,pad=8;setChatFabPosition({x:Math.max(pad,Math.min(window.innerWidth-size-pad,e.clientX-drag.offsetX)),y:Math.max(pad,Math.min(window.innerHeight-size-pad,e.clientY-drag.offsetY))})};
 const endChatFabDrag=(e:React.PointerEvent<HTMLButtonElement>)=>{const drag=chatFabDrag.current;if(!drag||drag.pointerId!==e.pointerId)return;chatFabDrag.current=null;e.currentTarget.releasePointerCapture(e.pointerId);if(!drag.moved)setMobileChatOpen(true)};
 const roleText=human.role==='miner'?'THỢ ĐÀO':'SÓI';
 const playerExp=Math.max(0,profile?.exp||0);const playerLevel=levelFromExp(playerExp);const levelStart=expForLevel(playerLevel);const levelEnd=expForLevel(playerLevel+1);const levelProgress=Math.min(100,Math.max(0,((playerExp-levelStart)/Math.max(1,levelEnd-levelStart))*100));
 if(roomAccess==='checking')return <section className="center-page"><div className="auth-card"><Pickaxe className="spin-slow"/><h1>ĐANG XÁC MINH PHÒNG</h1></div></section>;
 if(roomAccess==='denied')return <section className="center-page"><div className="auth-card"><Shield/><h1>KHÔNG THỂ VÀO TRẬN</h1><p>Phòng không hợp lệ, chưa bắt đầu hoặc bạn không thuộc phòng này.</p><button className="btn btn-primary" onClick={()=>navigate('/room',{replace:true})}>VỀ PHÒNG CHỜ</button></div></section>;
 return <section className={`game-page ${profile?.equipped.boardSkin||'board-default'} ${profile?.equipped.pieceSkin||'piece-default'}`} ref={gameRef}>
  <div className="orientation-hint" role="dialog" aria-modal="true" aria-label="Yêu cầu xoay ngang màn hình"><div className="orientation-hint-card"><span className="orientation-phone"><RotateCcw aria-hidden="true"/></span><span className="eyebrow">TRẢI NGHIỆM MOBILE</span><h2>VUI LÒNG XOAY NGANG MÀN HÌNH</h2><p>Trò chơi trên điện thoại chỉ khả dụng ở chế độ màn hình ngang.</p></div></div>
  {showFullscreenPrompt&&<div className="fullscreen-prompt"><div className="fullscreen-card"><button className="prompt-close" onClick={()=>setShowFullscreenPrompt(false)}><X/></button><span className="eyebrow">CHẾ ĐỘ TRẬN ĐẤU</span><h2>SẴN SÀNG ĐÀO VÀNG?</h2><p>Khuyến nghị bật toàn màn hình để thấy trọn bàn cờ và bảng điều khiển.</p><button className="btn btn-primary btn-wide" onClick={()=>void chooseFullscreen(true)}><Expand/> BẬT TOÀN MÀN HÌNH</button><button className="btn btn-ghost btn-wide" onClick={()=>void chooseFullscreen(false)}>CHƠI BÌNH THƯỜNG</button><label><input type="checkbox" checked={rememberFullscreen} onChange={e=>setRememberFullscreen(e.target.checked)}/> Ghi nhớ lựa chọn</label><small>Nhấn <b>F</b> để bật/tắt fullscreen.</small></div></div>}
   <div className="game-top"><div><span>{`MAP: ${state.map.id.toUpperCase()}`}</span><h1>{state.map.name}</h1></div><div className="hud-status"><div className="turn-pill"><Clock3/> {state.winner?'TRẬN ĐÃ KẾT THÚC':aiThinking?`${current.name} ĐANG SUY NGHĨ...`:current?.isBot?`${current.name} ĐANG ĐI`:'ĐẾN LƯỢT BẠN'}</div></div><div className="game-actions"><span className={`ping-badge ${ping===null?'offline':ping<100?'good':ping<220?'medium':'bad'}`} title="Độ trễ mạng"><b>{ping===null?'--':ping}</b><small>ms</small></span><button aria-label="Cài đặt" title="Cài đặt" className="btn btn-ghost btn-small action-settings" onClick={()=>setShowPlayersModal(true)}><Settings/><span>Cài đặt</span></button><button aria-label={isFullscreen?'Thu nhỏ':'Toàn màn hình'} title={isFullscreen?'Thu nhỏ':'Toàn màn hình'} className="btn btn-ghost btn-small action-fullscreen" onClick={()=>void toggleFullscreen()}>{isFullscreen?<Minimize/>:<Expand/>}<span>{isFullscreen?'Thu nhỏ':'Toàn màn hình'}</span></button><button aria-label="Rời bàn" title="Rời bàn" className="btn btn-danger btn-small action-leave" onClick={()=>setShowLeaveConfirm(true)}><DoorOpen/><span>Rời bàn</span></button></div></div>
  <button className={`mobile-chat-fab ${chatFabPosition?'is-dragged':''}`} style={chatFabPosition?{'--chat-x':`${chatFabPosition.x}px`,'--chat-y':`${chatFabPosition.y}px`} as React.CSSProperties:undefined} onPointerDown={startChatFabDrag} onPointerMove={moveChatFab} onPointerUp={endChatFabDrag} onPointerCancel={()=>{chatFabDrag.current=null}} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setMobileChatOpen(true)}}} aria-label="Mở hoặc di chuyển trò chuyện"><MessageCircle/><span>TRÒ CHUYỆN</span></button>
  {mobilePlayerMenuOpen&&<div className="mobile-player-menu-backdrop" onClick={()=>setMobilePlayerMenuOpen(false)}><div className="mobile-player-menu" role="menu" onClick={e=>e.stopPropagation()}><button role="menuitem" onClick={()=>{setMobilePlayerMenuOpen(false);setShowPlayersModal(true)}}><Settings/> CÀI ĐẶT</button><button role="menuitem" className="danger" onClick={()=>{setMobilePlayerMenuOpen(false);setShowLeaveConfirm(true)}}><DoorOpen/> RỜI BÀN</button></div></div>}
  <div className="game-layout-v5">
    <main className="board-wrap">
      <div className="mine-board-shell dynamic">
        <div className="mine-entrance" aria-label="Cửa hầm"><span><Pickaxe aria-hidden="true"/></span><b>CỬA HẦM</b><i/></div>
        <div className="board dynamic-board" style={{gridTemplateColumns:`repeat(${state.map.cols},1fr)`,gridTemplateRows:`repeat(${state.map.rows},1fr)`}}>{state.board.map((row,r)=>row.map((cell,c)=>{const legal=playable&&human.blockedTurns<=0&&selectedCard?.type==='path'&&!cell&&isValidPlacement(state.board,selectedCard,r,c,state.map,state.obstacles);const obstacle=state.obstacles.includes(`${r},${c}`);return <button disabled={obstacle} onClick={()=>clickCell(r,c)} key={`${r}-${c}`} className={`cell ${cell?'occupied':''} ${legal?'legal':''} ${obstacle?'obstacle':''}`}><span className="grid-coord">{String.fromCharCode(65+c)}{r+1}</span>{obstacle?<div className="obstacle-art cliff"><img className="mine-rock-sprite" src="/images/board-skins/mine-rock.png" alt="Vách đá"/></div>:cell&&<TunnelSvg card={cell.card} small/>}</button>}))}</div>
        <div className="treasure-column compact" style={{gridTemplateRows:`repeat(${state.map.rows},1fr)`}}>{state.map.objectives.map(o=>{const t=state.treasures.find(x=>x.id===o.id)!;const peek=t.peekedBy.includes(human.id);return <button onClick={()=>clickTreasure(o.id)} key={o.id} className={`treasure-slot ${t.revealed?'revealed':''} ${t.revealed&&t.isGold?'gold':''} ${peek?'peeked':''} ${peek?(t.isGold?'peeked-gold':'peeked-fake'):''}`} style={{gridRow:(o.row??0)+1}} title={t.revealed?(t.isGold?'Kho báu thật':'Rương giả'):peek?(t.isGold?'Bạn đã thăm dò: KHO BÁU THẬT':'Bạn đã thăm dò: RƯƠNG GIẢ'):'Rương bí ẩn'}><span>{peek||t.revealed?(t.isGold?<Gem aria-hidden="true"/>:<Mountain aria-hidden="true"/>):<img className="treasure-chest-sprite" src="/images/board-skins/treasure-chest.png" alt="Rương kho báu"/>}</span>{peek&&!t.revealed&&<b>{t.isGold?'THẬT':'GIẢ'}</b>}</button>})}</div>
      </div>
    </main>
    <aside className={`battle-right-column ${mobileChatOpen?'mobile-chat-open':''}`}>
      <button className="mobile-chat-close" onClick={()=>setMobileChatOpen(false)} aria-label="Đóng trò chuyện"><X/> ĐÓNG</button>
      <section className="battle-journal panel" ref={logRef}>
        <ChatPanel compact systemMessages={state.logs.slice(0,20)} roomId={searchParams.get('room')||`match-${state.matchId}`}/>
      </section>
    </aside>
  </div>
  <div className="mobile-turn-strip"><Clock3/>{state.winner?'TRẬN ĐÃ KẾT THÚC':aiThinking?`${current.name} ĐANG SUY NGHĨ...`:current?.isBot?`${current.name} ĐANG ĐI`:'ĐẾN LƯỢT BẠN'}</div>
  <footer className="game-bottom-hud redesigned-bottom-hud">
    <div className="player-hand-row">
    <section className="player-progress-card">
      <div className="progress-avatar-wrap"><button type="button" className="progress-avatar" aria-label="Mở menu người chơi" onClick={()=>setMobilePlayerMenuOpen(v=>!v)}>{profile?.photoURL?<img src={profile.photoURL} alt=""/>:<UserRound/>}</button><i className="online-dot"/></div>
      <div className="progress-player-copy"><div className="progress-name-line"><b>{human.name}</b><span><Sparkles/> LV. {playerLevel}</span></div><strong className={human.role}>{roleText}</strong><div className="exp-values"><small>{playerExp.toLocaleString('vi-VN')} / {levelEnd.toLocaleString('vi-VN')}</small></div><div className="exp-track"><i style={{width:`${levelProgress}%`}}/></div></div>
    </section>
    <section className={`hand-hud-panel ${!playable?'is-waiting':''}`}><header><b>HƯỚNG ĐI</b><small>{sabotageMode?'Chọn đường cần phá':selected===null?'Chọn một lá để sử dụng':human.hand[selected]?.label}</small></header><div className="hand-hud-cards">{human.hand.map((card,i)=><button data-slot={i+1} onClick={()=>select(i)} className={`hand-hud-card ${card.type} ${card.kind} ${human.blockedTurns>0&&card.type==='path'?'movement-locked':''} ${selected===i?'selected':''}`} key={card.id} title={human.blockedTurns>0&&card.type==='path'?'Đang bị Chặn: chỉ có thể bỏ lá này':card.label}><span><TunnelSvg card={card}/></span><b>{card.label}</b><small>{card.type==='path'?'ĐƯỜNG':'CHỨC NĂNG'}</small></button>)}</div><button className="hand-hud-discard" disabled={!playable||selected===null} onClick={discardSelected}><Trash2/><span>BỎ BÀI</span></button>
    {human.canSabotage&&<section className="bottom-special-hand wolf-only-skill">
      <header><span>KỸ NĂNG SÓI</span><small>Kỹ năng bí mật dùng một lần</small></header>
      <div className="bottom-special-grid"><button className={`bottom-special-card sabotage ${sabotageMode?'selected':''}`} disabled={!playable||human.sabotageUsed} onClick={()=>{setSelected(null);setSabotageMode(v=>!v)}}><Hammer/><span><em>KỸ NĂNG SÓI</em><b>PHÁ SẬP HẦM</b><small>Phá tâm và 4 mảnh kề · dùng 1 lần</small></span></button></div>
    </section>}
    </section>
    </div>
  </footer>

  {state.winner&&matchRewards&&<div className="match-summary-modal"><div className="match-summary-card"><header><div><span className="eyebrow">TỔNG KẾT TRẬN ĐẤU</span><h2>{state.winner==='miners'?'THỢ ĐÀO CHIẾN THẮNG':'SÓI CHIẾN THẮNG'}</h2><p>Vai trò đã được công khai. Vàng và EXP chỉ được cộng sau khi trận hoàn tất.</p></div><Trophy aria-hidden="true"/></header><div className="match-summary-table"><div className="summary-head"><span>NGƯỜI CHƠI</span><span>VAI TRÒ</span><span>KẾT QUẢ</span><span>VÀNG</span><span>EXP</span></div>{state.players.map((p,i)=>{const won=state.winner===(p.role==='miner'?'miners':'wolves');const reward=matchRewards[p.id];return <div className={`summary-row ${i===humanIndex?'is-you':''} ${won?'is-winner':''}`} key={p.id}><span className="summary-player"><i>{p.isBot?<Bot aria-hidden="true"/>:<UserRound aria-hidden="true"/>}</i><b>{p.name}{i===humanIndex?' (Bạn)':''}</b></span><span><strong className={`role-chip ${p.role}`}>{p.role==='miner'?'THỢ ĐÀO':p.canSabotage?'SÓI PHÁ HẦM':'SÓI'}</strong></span><span><strong className={won?'result-win':'result-loss'}>{won?'THẮNG':'THUA'}</strong></span><span className="reward-value coins"><Coins/> +{reward.coins}</span><span className="reward-value exp"><Sparkles/> +{reward.exp}</span></div>})}</div><footer><div className="your-reward"><small>PHẦN THƯỞNG CỦA BẠN</small><b><Coins/> +{matchRewards[human.id].coins} vàng</b><b><Sparkles/> +{matchRewards[human.id].exp} EXP</b><span>{statsSaved?'Đã ghi nhận vào hồ sơ.':'Đang ghi nhận phần thưởng...'}</span></div><button className="btn btn-primary" onClick={()=>void leaveTable()}>HOÀN TẤT & RỜI BÀN</button></footer></div></div>}

  {special&&<div className="leave-modal special-modal" onMouseDown={e=>{if(e.target===e.currentTarget){setSpecial(null);setTargetPlayer(null);setMySwapCard(null)}}}><div className={`leave-card special-card skill-${special}`}><button className="prompt-close" onClick={()=>{setSpecial(null);setTargetPlayer(null);setMySwapCard(null)}}><X/></button><div className="special-hero-icon">{special==='block'?<Ban aria-hidden="true"/>:special==='revive'?<HeartPulse aria-hidden="true"/>:<RefreshCcw aria-hidden="true"/>}</div><span className="eyebrow">LÁ ĐẶC BIỆT</span><h2>{special==='block'?'CHẶN ĐƯỜNG':special==='revive'?'HỒI SINH':'ĐỔI BÀI ÚP'}</h2>{special==='swap'&&mySwapCard===null?<><p>Chọn một lá bài của bạn để mang đi đổi.</p><div className="swap-my-cards">{human.hand.map((c,i)=><button key={c.id} onClick={()=>setMySwapCard(i)}><TunnelSvg card={c} small/><b>{c.label}</b></button>)}</div></>:targetPlayer===null?<><p>{special==='revive'?'Chọn chính bạn hoặc một người khác đang bị Chặn.':special==='swap'?'Chọn người chơi bạn muốn đổi bài.':'Chọn người chơi mục tiêu.'}</p><div className="special-player-list">{state.players.map((p,i)=>special==='block'&&i===humanIndex?null:<button disabled={(special==='revive'&&p.blockedTurns<=0)||(special==='block'&&p.blockedTurns>0)} key={p.id} onClick={()=>useSpecialTarget(i)}><span>{i===humanIndex?<UserRound aria-hidden="true"/>:p.isBot?<Bot aria-hidden="true"/>:<UserRound aria-hidden="true"/>}</span><b>{p.name}{i===0?' (Bạn)':''}</b><small>{p.blockedTurns>0?'ĐANG BỊ CHẶN':`${p.hand.length} lá úp`}</small></button>)}</div></>:<><p>Chọn một lá đang úp của {state.players[targetPlayer].name}. Bạn chỉ biết lá gì sau khi đổi.</p><div className="facedown-cards">{state.players[targetPlayer].hand.map((_,i)=><button key={i} onClick={()=>finishSwap(i)}><span><Box aria-hidden="true"/></span><b>LÁ {i+1}</b></button>)}</div></>}</div></div>}

  {showPlayersModal&&<div className="leave-modal players-settings-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setShowPlayersModal(false)}}><div className="leave-card players-settings-card"><button className="prompt-close" onClick={()=>setShowPlayersModal(false)}><X/></button><div className="mobile-settings-compact"><Settings/><div><b>NGƯỜI CHƠI</b><small>{state.players.length} người trong trận</small></div></div><div className="mobile-settings-player-list">{state.players.map((p,i)=><div className={`mobile-settings-player ${state.turn===i?'active':''}`} key={p.id}><span className="mobile-settings-avatar">{i===humanIndex&&profile?.photoURL?<img src={profile.photoURL} alt=""/>:p.isBot?<Bot/>:<UserRound/>}</span><div><b>{p.name}{i===0?' (Bạn)':''}</b><small>LV. {i===humanIndex?playerLevel:1} · {i===0?(profile?.rank||'Tân binh'):'Tân binh'}</small></div>{state.turn===i&&<i>ĐANG ĐI</i>}</div>)}</div><div className="settings-modal-head"><Settings/><div><span className="eyebrow">CÀI ĐẶT TRẬN ĐẤU</span><h2>NGƯỜI CHƠI</h2></div></div><div className="settings-player-list">{state.players.map((p,i)=><div className={`player-row ${state.turn===i?'active':''}`} key={p.id}><PlayerIdentity compact active={state.turn===i} player={{name:i===0?`${p.name} - ${roleText}`:p.name,bot:p.isBot,photoURL:i===humanIndex?profile?.photoURL:'',rank:i===humanIndex?profile?.rank:undefined,equipped:i===humanIndex?profile?.equipped:undefined}} hideSubtitle/>{i!==humanIndex&&!p.isBot&&<button className="report-mini" onClick={()=>setReportTarget(i)}>BÁO CÁO</button>}</div>)}</div><button className="btn btn-primary btn-wide settings-close-button" onClick={()=>setShowPlayersModal(false)}>ĐÓNG</button></div></div>}
  {reportTarget!==null&&<div className="leave-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setReportTarget(null)}}><div className="leave-card report-card"><button className="prompt-close" onClick={()=>setReportTarget(null)}><X/></button><Shield/><span className="eyebrow">BÁO CÁO NGƯỜI CHƠI</span><h2>{state.players[reportTarget]?.name}</h2><select value={reportReason} onChange={e=>setReportReason(e.target.value)}><option>AFK</option><option>Spam</option><option>Tên phản cảm</option><option>Phá game</option><option>Nghi gian lận</option></select><button className="btn btn-danger btn-wide" onClick={async()=>{if(!db||!profile||reportTarget===null)return;const target=state.players[reportTarget];const id=`${state.matchId}_${profile.uid}_${target.id}`;try{await setDoc(doc(db,'reports',id),{matchId:state.matchId,reporterUid:profile.uid,targetId:target.id,targetName:target.name,reason:reportReason,createdAt:serverTimestamp()});setReportMessage('Đã gửi báo cáo.');setReportTarget(null)}catch(e:any){setReportMessage(e?.message||'Không thể gửi báo cáo.')}}}>GỬI BÁO CÁO</button></div></div>}
  {reportMessage&&<div className="game-toast" onClick={()=>setReportMessage('')}>{reportMessage}</div>}
  {showLeaveConfirm&&<div className="leave-modal" onMouseDown={e=>{if(e.target===e.currentTarget)setShowLeaveConfirm(false)}}><div className="leave-card"><DoorOpen/><span className="eyebrow">XÁC NHẬN</span><h2>RỜI BÀN?</h2><p>Bạn có chắc muốn rời trận? Tiến trình hiện tại sẽ không được giữ lại.</p><div><button className="btn btn-ghost" onClick={()=>setShowLeaveConfirm(false)}>Ở LẠI</button><button className="btn btn-danger" onClick={()=>void leaveTable()}>RỜI BÀN</button></div></div></div>}
 </section>
}
