import { useEffect, useState } from 'react';
import { Check, Coins, Gift, Sparkles, Target, Trophy, Gamepad2, MessageCircle, Timer, Crown, ShoppingBag, Vault, Medal } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { levelProgress, nextRank, rankFromPoints } from '../lib/progression';
import { MISSIONS, missionProgress, secondsUntilDailyReset, todayKey, type Mission } from '../lib/missions';
import GameEmblem from '../components/GameEmblem';
const missionIcon=(m:Mission)=>m.metric==='online'?Timer:m.metric==='dailyGames'||m.metric==='gamesPlayed'?Gamepad2:m.metric==='dailyWins'||m.metric==='wins'?Crown:m.metric==='dailyChats'?MessageCircle:m.metric==='ownedItems'?ShoppingBag:m.metric==='coins'?Vault:m.metric==='level'||m.metric==='rankPoints'?Medal:Target;
const clock=(seconds:number)=>`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
export default function Missions(){
 const{profile,claimMission}=useAuth();const[resetIn,setResetIn]=useState(secondsUntilDailyReset());useEffect(()=>{const timer=window.setInterval(()=>setResetIn(secondsUntilDailyReset()),1000);return()=>window.clearInterval(timer)},[]);if(!profile)return null;
 const data=profile.missionDate===todayKey()?profile:{...profile,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]},level=levelProgress(profile.exp),tier=rankFromPoints(profile.rankPoints),up=nextRank(profile.rankPoints);
 const summary=(kind:'daily'|'achievement')=>{const list=MISSIONS.filter(m=>m.kind===kind),ids=kind==='daily'?data.claimedDailyMissions:profile.claimedAchievements;return`${list.filter(m=>ids.includes(m.id)).length}/${list.length}`};
 const render=(kind:'daily'|'achievement')=><div className="mission-grid">{MISSIONS.filter(m=>m.kind===kind).map(m=>{const progress=missionProgress(m,data),done=progress>=m.target,claimed=(m.kind==='daily'?data.claimedDailyMissions:profile.claimedAchievements).includes(m.id),percent=Math.min(100,Math.round(progress/m.target*100)),Icon=missionIcon(m);return <article className={`mission-card ${done?'done':''} ${claimed?'claimed':''}`} key={m.id}><div className="mission-icon"><GameEmblem icon={claimed?Check:Icon} tone={claimed?'emerald':kind==='daily'?'gold':'violet'}/></div><div className="mission-main"><span>{kind==='daily'?'NHIỆM VỤ NGÀY':'THÀNH TỰU'}</span><h3>{m.title}</h3><p>{m.description}</p><div className="mission-progress"><i style={{width:`${percent}%`}}/><em>{percent}%</em></div><small>{Math.min(progress,m.target).toLocaleString('vi-VN')} / {m.target.toLocaleString('vi-VN')}</small></div><div className="mission-reward"><div className="reward-chip coin"><Coins/> <b>+{m.rewardCoins}</b></div><div className="reward-chip exp"><Sparkles/> <b>+{m.rewardExp} EXP</b></div><button className="btn btn-small btn-primary" disabled={!done||claimed} onClick={()=>void claimMission(m.id)}>{claimed?'ĐÃ NHẬN':done?'NHẬN THƯỞNG':'CHƯA HOÀN THÀNH'}</button></div></article>})}</div>;
 return <section className="missions-page ui-v2-page"><header className="missions-hero"><div><span>TRUNG TÂM TIẾN TRÌNH</span><h1>HÀNH TRÌNH THỢ MỎ</h1><p>Level ghi nhận kinh nghiệm lâu dài. Rank phản ánh kết quả thi đấu và thay đổi sau mỗi trận.</p><div className="progression-summary"><div><small>LEVEL {level.level}</small><b>{level.isMax?'TỐI ĐA':`${level.current}/${level.required} EXP`}</b><i><em style={{width:`${level.percent}%`}}/></i></div><div><small>RANK {tier.name}</small><b>{profile.rankPoints.toLocaleString('vi-VN')} RP {up?`· còn ${up.min-profile.rankPoints} RP`:''}</b><i><em style={{width:`${up?Math.max(0,Math.min(100,(profile.rankPoints-tier.min)/(up.min-tier.min)*100)):100}%`}}/></i></div></div></div><div className="mission-level"><GameEmblem icon={Crown} size="lg" tone="violet"/><small>{tier.name.toUpperCase()}</small><b>{profile.rankPoints}</b><em>RANK POINT</em></div></header><div className="mission-section-title"><GameEmblem icon={Gift}/><div><h2>NHIỆM VỤ HẰNG NGÀY <span className="mission-count">{summary('daily')}</span></h2><p>Làm mới sau <b>{clock(resetIn)}</b> · múi giờ Việt Nam.</p></div></div>{render('daily')}<div className="mission-section-title"><GameEmblem icon={Trophy} tone="violet"/><div><h2>THÀNH TỰU <span className="mission-count">{summary('achievement')}</span></h2><p>Cột mốc vĩnh viễn, mỗi phần thưởng chỉ nhận một lần.</p></div></div>{render('achievement')}</section>;
}
