import { useEffect, useState } from 'react';
import { Check, Coins, Gift, Sparkles, Trophy, Crown, CalendarDays, GraduationCap, Flag, CalendarRange } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { levelProgress, rankFromPoints } from '../lib/progression';
import { MISSION_GROUPS, missionProgress, secondsUntilDailyReset, todayKey, weekKey, type MissionKind } from '../lib/missions';
import GameEmblem from '../components/GameEmblem';
const clock=(seconds:number)=>`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
const icons={daily:CalendarDays,progression:GraduationCap,basic:Flag,weekly:CalendarRange};
export default function Missions(){
 const{profile,claimMission}=useAuth();const[resetIn,setResetIn]=useState(secondsUntilDailyReset());useEffect(()=>{const timer=window.setInterval(()=>setResetIn(secondsUntilDailyReset()),1000);return()=>window.clearInterval(timer)},[]);if(!profile)return null;
 const data={...profile,...(profile.missionDate===todayKey()?{}:{onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]}),...(profile.weekDate===weekKey()?{}:{weeklyGames:0,weeklyWins:0,weeklyChats:0,claimedWeeklyMissions:[]})},level=levelProgress(profile.exp),tier=rankFromPoints(profile.rankPoints);
 const claimedIds=(kind:MissionKind)=>kind==='daily'?data.claimedDailyMissions:kind==='weekly'?data.claimedWeeklyMissions:data.claimedAchievements;
 return <section className="missions-page ui-v2-page"><header className="missions-hero"><div><span>TRUNG TÂM NHIỆM VỤ</span><h1>HÀNH TRÌNH THỢ MỎ</h1><p>Hoàn thành thử thách, nhận EXP và vàng để phát triển hồ sơ của bạn.</p><div className="mission-overview"><div><small>LEVEL</small><b>{level.level}</b><span>{level.isMax?'Tối đa':`${level.current}/${level.required} EXP`}</span></div><div><small>RANK</small><b>{tier.name}</b><span>{profile.rankPoints} RP</span></div><div><small>DAILY RESET</small><b>{clock(resetIn)}</b><span>Giờ Việt Nam</span></div></div></div><div className="mission-level"><GameEmblem icon={Crown} size="lg" tone="violet"/><small>TIẾN ĐỘ</small><b>{MISSION_GROUPS.flatMap(g=>g.missions).filter(m=>claimedIds(m.kind).includes(m.id)).length}</b><em>NHIỆM VỤ ĐÃ NHẬN</em></div></header>
 <nav className="mission-category-nav">{MISSION_GROUPS.map(group=>{const Icon=icons[group.kind],done=group.missions.filter(m=>claimedIds(group.kind).includes(m.id)).length;return <a href={`#mission-${group.kind}`} key={group.kind}><Icon/><span>{group.title}<small>{done}/{group.missions.length} hoàn thành</small></span></a>})}</nav>
 {MISSION_GROUPS.map(group=>{const Icon=icons[group.kind],claimed=claimedIds(group.kind);return <section className="mission-category" id={`mission-${group.kind}`} key={group.kind}><div className="mission-section-title"><GameEmblem icon={Icon} tone={group.kind==='weekly'||group.kind==='progression'?'violet':'gold'}/><div><h2>{group.title}</h2><p>{group.kind==='daily'?`Làm mới sau ${clock(resetIn)}.`:group.description}</p></div><strong>{claimed.length}/{group.missions.length}</strong></div><div className="mission-list">{group.missions.map(m=>{const progress=missionProgress(m,data),done=progress>=m.target,isClaimed=claimed.includes(m.id),percent=Math.min(100,Math.round(progress/m.target*100));return <article className={`mission-row ${done?'done':''} ${isClaimed?'claimed':''}`} key={m.id}><div className="mission-check">{done?<Check/>:<span/>}</div><div className="mission-copy"><h3>{m.title}</h3><p>{m.description}</p><div className="mission-progress"><i style={{width:`${percent}%`}}/><em>{Math.min(progress,m.target).toLocaleString('vi-VN')} / {m.target.toLocaleString('vi-VN')}</em></div></div><div className="mission-row-reward"><span><Coins/>+{m.rewardCoins}</span><span><Sparkles/>+{m.rewardExp} EXP</span><button className="btn btn-small btn-primary" disabled={!done||isClaimed} onClick={()=>void claimMission(m.id)}>{isClaimed?'ĐÃ NHẬN':done?'NHẬN':'ĐANG LÀM'}</button></div></article>})}</div></section>})}
 </section>;
}
