import { useEffect, useState, type CSSProperties } from 'react';
import { Award, BadgeCheck, Check, Coins, Crown, Gauge, PackageOpen, Pickaxe, ShieldAlert, Swords, UserMinus, UserPlus, X } from 'lucide-react';
import { collection, getDocs, limit, query } from 'firebase/firestore';
import { useParams } from 'react-router-dom';
import { Profile as ProfileData, useAuth } from '../context/AuthContext';
import { db } from '../lib/firebase';
import { expForLevel, levelFromExp, rankFromPoints, rankStars } from '../lib/progression';
import { MISSIONS } from '../lib/missions';
import { cosmeticClass, itemById, SHOP_ITEMS, ShopCategory } from '../lib/shop';
import { acceptFriendRequest, cancelFriendRequest, friendshipStatus, FriendshipStatus, removeFriend, sendFriendRequest, summaryOf } from '../lib/friends';
import CosmeticPreview from '../components/CosmeticPreview';
import { nameSlug } from '../lib/slugs';

const categoryName:Record<ShopCategory,string>={frame:'Khung hồ sơ',nameColor:'Màu tên',nameplate:'Nền bảng tên',title:'Danh xưng',badge:'Huy hiệu',boardSkin:'Skin bàn cờ',pieceSkin:'Skin quân cờ'};
type InventoryFilter='all'|ShopCategory;
const inventoryFilters:Array<{id:InventoryFilter;label:string}>=[{id:'all',label:'TẤT CẢ'},{id:'boardSkin',label:'BÀN CỜ'},{id:'pieceSkin',label:'QUÂN CỜ'},{id:'frame',label:'KHUNG AVATAR'},{id:'nameColor',label:'MÀU TÊN'},{id:'nameplate',label:'NỀN BẢNG TÊN'},{id:'title',label:'DANH HIỆU'},{id:'badge',label:'HUY HIỆU'}];
const publicProfile=(uid:string,data:Record<string,unknown>):ProfileData=>{
 const number=(key:string)=>Math.max(0,Number(data[key]||0));
 const rankPoints=number('rankPoints');
 return{uid,displayName:String(data.displayName||'Người chơi'),email:'',photoURL:String(data.photoURL||''),rank:rankFromPoints(rankPoints).label,rankPoints,highestRankPoints:number('highestRankPoints'),winStreak:number('winStreak'),bestWinStreak:number('bestWinStreak'),claimedRankRewards:[],exp:number('exp'),coins:0,wins:number('wins'),losses:number('losses'),gamesPlayed:number('gamesPlayed'),ownedItems:[],equipped:data.equipped&&typeof data.equipped==='object'?data.equipped as ProfileData['equipped']:{},missionDate:'',onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,weekDate:'',weeklyGames:0,weeklyWins:0,weeklyChats:0,claimedDailyMissions:[],claimedWeeklyMissions:[],claimedAchievements:Array.isArray(data.claimedAchievements)?data.claimedAchievements.filter((id):id is string=>typeof id==='string'):[]};
};

export default function Profile(){
 const{name}=useParams();const{profile,login,equipItem,unequipItem}=useAuth();const[msg,setMsg]=useState('');const[remote,setRemote]=useState<ProfileData|null>(null);const[loading,setLoading]=useState(false);const[notFound,setNotFound]=useState(false);const[relation,setRelation]=useState<FriendshipStatus>('none');
 const[inventoryFilter,setInventoryFilter]=useState<InventoryFilter>('all');
 const ownProfile=!name||nameSlug(profile?.displayName||'')===name;
 useEffect(()=>{if(ownProfile){setRemote(null);setNotFound(false);return}if(!name||!db)return;let active=true;setLoading(true);setNotFound(false);void getDocs(query(collection(db,'users'),limit(500))).then(snapshot=>{if(!active)return;const match=snapshot.docs.find(item=>nameSlug(String(item.data().displayName||''))===name);if(!match){setNotFound(true);setRemote(null)}else setRemote(publicProfile(match.id,match.data()))}).catch(()=>{if(active)setNotFound(true)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[name,ownProfile]);
 useEffect(()=>{if(!profile||!remote||ownProfile){setRelation('none');return}let active=true;void friendshipStatus(profile.uid,remote.uid).then(status=>{if(active)setRelation(status)});return()=>{active=false}},[profile?.uid,remote?.uid,ownProfile]);
 if(!profile)return <section className="center-page"><button className="btn btn-primary" onClick={login}>ĐĂNG NHẬP GOOGLE</button></section>;
 if(loading)return <section className="center-page"><div className="auth-card"><Pickaxe className="spin-slow"/><h1>ĐANG TẢI HỒ SƠ</h1></div></section>;
 if(notFound||(!ownProfile&&!remote))return <section className="center-page"><div className="auth-card"><ShieldAlert/><h1>KHÔNG TÌM THẤY HỒ SƠ</h1><p>Người chơi này không tồn tại hoặc hồ sơ không còn khả dụng.</p></div></section>;
 const viewed=ownProfile?profile:remote!;
 const total=viewed.wins+viewed.losses,level=levelFromExp(viewed.exp),start=expForLevel(level),end=expForLevel(level+1),progress=Math.round((viewed.exp-start)/Math.max(1,end-start)*100),title=itemById(viewed.equipped.title)?.name,rankInfo=rankFromPoints(viewed.rankPoints),stars=rankStars(viewed.rankPoints),highestRankInfo=rankFromPoints(viewed.highestRankPoints),highestStars=rankStars(viewed.highestRankPoints);
 const ownedItems=ownProfile?SHOP_ITEMS.filter(item=>viewed.ownedItems.includes(item.id)):[];
 const visibleOwnedItems=ownedItems.filter(item=>inventoryFilter==='all'||item.category===inventoryFilter);
 const equippedItems=Object.values(viewed.equipped).map(id=>itemById(id)).filter((item):item is NonNullable<ReturnType<typeof itemById>>=>Boolean(item));
 const achievements=MISSIONS.filter(mission=>(mission.kind==='basic'||mission.kind==='progression')&&viewed.claimedAchievements.includes(mission.id));
 const act=async(action:()=>Promise<void>,message:string)=>{try{await action();setMsg(message)}catch(error:any){setMsg(error?.message||'Không thể cập nhật tủ đồ.')}};
 const social=async(action:()=>Promise<void>,next:FriendshipStatus,message:string)=>{try{await action();setRelation(next);setMsg(message)}catch(error:any){setMsg(error?.message||'Không thể cập nhật quan hệ bạn bè.')}};
 return <section className={`profile-page ${ownProfile?'is-own-profile':'is-public-profile'}`}>
  <div className={`profile-banner profile-career-banner ${cosmeticClass(viewed.equipped.nameplate)}`}><div className="profile-banner-main"><div className={`large-avatar ${cosmeticClass(viewed.equipped.frame)}`}>{viewed.photoURL?<img src={viewed.photoURL} alt=""/>:<Pickaxe/>}{viewed.equipped.badge&&<i className={`identity-badge ${cosmeticClass(viewed.equipped.badge)}`}><BadgeCheck/></i>}</div><div className="profile-banner-copy"><span>{ownProfile?'HỒ SƠ THỢ MỎ':'HỒ SƠ NGƯỜI CHƠI'}</span><h1 className={cosmeticClass(viewed.equipped.nameColor)}>{viewed.displayName}</h1>{title&&<p className="profile-title-line"><strong className={`equipped-title ${cosmeticClass(viewed.equipped.title)}`}>{title}</strong></p>}<div className="profile-rank-badges"><strong className="profile-rank-badge" style={{'--rank-color':rankInfo.color} as CSSProperties}><Crown/><span>{rankInfo.label}<small className="rank-star-count">★ {stars}</small></span></strong><strong className="profile-level-badge"><Gauge/><span><small>Lv.</small>{level}</span></strong></div><div className="profile-exp"><i style={{width:`${Math.max(0,Math.min(100,progress))}%`}}/><span>{viewed.exp-start}/{end-start} EXP tới cấp {level+1}</span></div></div>{ownProfile&&<div className="profile-currency"><Coins/><b>{viewed.coins}</b><span>VÀNG</span></div>}</div><section className="profile-career-stats"><header><Gauge/> THỐNG KÊ SỰ NGHIỆP</header><div><article><Swords/><span><b>{total}</b><small>Tổng trận</small></span></article><article><Crown/><span><b>{viewed.wins}</b><small>Chiến thắng</small></span></article><article><ShieldAlert/><span><b>{total?Math.round(viewed.wins/total*100):0}%</b><small>Tỷ lệ thắng</small></span></article><article><Pickaxe/><span><b>{viewed.exp}</b><small>EXP tích lũy</small></span></article><article><Crown/><span><b>{highestRankInfo.label}</b><small>Rank cao nhất · ★ {highestStars} sao</small></span></article><article><Swords/><span><b>×{viewed.winStreak}</b><small>Chuỗi thắng · tốt nhất {viewed.bestWinStreak}</small></span></article></div></section></div>
  {!ownProfile&&<div className="profile-social-actions">{relation==='none'&&<button className="btn btn-primary" onClick={()=>void social(()=>sendFriendRequest(profile,summaryOf(viewed)),'sent','Đã gửi lời mời kết bạn.')}><UserPlus/> KẾT BẠN</button>}{relation==='sent'&&<button className="btn btn-ghost" onClick={()=>void social(()=>cancelFriendRequest(profile.uid,viewed.uid),'none','Đã thu hồi lời mời.')}><X/> THU HỒI LỜI MỜI</button>}{relation==='received'&&<button className="btn btn-primary" onClick={()=>void social(()=>acceptFriendRequest(profile,{...summaryOf(viewed),fromUid:viewed.uid,toUid:profile.uid}),'friends','Đã trở thành bạn bè.')}><Check/> CHẤP NHẬN KẾT BẠN</button>}{relation==='friends'&&<button className="btn btn-danger" onClick={()=>void social(()=>removeFriend(profile.uid,viewed.uid),'none','Đã huỷ kết bạn.')}><UserMinus/> HUỶ KẾT BẠN</button>}</div>}
  {msg&&<button className="profile-message" onClick={()=>setMsg('')}>{msg}<X/></button>}
  {!ownProfile&&<div className="profile-grid profile-grid-single"><div className="panel achievements"><header><Award/> DANH HIỆU ĐÃ MỞ KHÓA</header>{achievements.length?<div className="badge-list">{achievements.map(mission=><span key={mission.id}><BadgeCheck aria-hidden="true"/><b>{mission.title}</b><small>{mission.description}</small></span>)}</div>:<div className="profile-empty"><Award/><b>Chưa có danh hiệu</b><span>Danh hiệu thành tích sẽ xuất hiện tại đây.</span></div>}</div></div>}
  {ownProfile?<section className="panel profile-vault"><div className="profile-inventory"><header><PackageOpen/> TỦ ĐỒ <small>{ownedItems.length} vật phẩm sở hữu</small></header><nav className="inventory-tabs shop-tabs">{inventoryFilters.map(tab=><button key={tab.id} className={inventoryFilter===tab.id?'active':''} onClick={()=>setInventoryFilter(tab.id)}>{tab.label}</button>)}</nav>{visibleOwnedItems.length?<div className="inventory-grid">{visibleOwnedItems.map(item=>{const equipped=viewed.equipped[item.category]===item.id,requiredSkin=item.category==='boardSkin',profileCosmetic=['frame','nameColor','nameplate','title','badge'].includes(item.category);return <article className={equipped?'equipped':''} key={item.id}><CosmeticPreview item={item} name={viewed.displayName} photoURL={viewed.photoURL} className="inventory-preview"/><div>{!profileCosmetic&&<small>{categoryName[item.category]}</small>}<b>{item.name}</b><span>{item.description}</span></div><button disabled={equipped&&requiredSkin} className={`btn ${equipped&&!requiredSkin?'btn-danger':'btn-ghost'}`} onClick={()=>void act(()=>equipped?unequipItem(item.category):equipItem(item.id),equipped?'Đã tháo vật phẩm.':'Đã trang bị vật phẩm.')}>{equipped?(requiredSkin?'ĐANG DÙNG':'THÁO'):viewed.equipped[item.category]?'ĐỔI':'TRANG BỊ'}</button></article>})}</div>:<div className="profile-empty"><PackageOpen/><b>Chưa có vật phẩm trong mục này</b><span>Mua thêm vật phẩm trong Cửa hàng để bổ sung vào Tủ đồ.</span></div>}</div><aside className="profile-vault-achievements"><header><Award/> DANH HIỆU ĐÃ MỞ KHÓA <small>{achievements.length}</small></header>{achievements.length?<div className="badge-list">{achievements.map(mission=><span key={mission.id}><BadgeCheck aria-hidden="true"/><b>{mission.title}</b><small>{mission.description}</small></span>)}</div>:<div className="profile-empty"><Award/><b>Chưa có danh hiệu</b><span>Danh hiệu thành tích sẽ xuất hiện tại đây.</span></div>}</aside></section>
  :<section className="panel profile-inventory public-equipped"><header><PackageOpen/> ĐANG TRANG BỊ <small>{equippedItems.length} vật phẩm</small></header>{equippedItems.length?<div className="inventory-grid">{equippedItems.map(item=><article className="equipped" key={item.id}><div className="inventory-preview">{item.preview}</div><div><small>{categoryName[item.category]}</small><b>{item.name}</b><span>{item.description}</span></div></article>)}</div>:<div className="profile-empty"><PackageOpen/><b>Chưa trang bị vật phẩm</b></div>}</section>}
 </section>;
}
