import { useEffect, useState } from 'react';
import { addDoc, collection, doc, getDocs, limit, onSnapshot, orderBy, query, serverTimestamp, updateDoc, where } from 'firebase/firestore';
import { Bot, Copy, DoorOpen, Globe2, LockKeyhole, Pickaxe, Plus, Radio, UserRound, Users } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';import { db } from '../lib/firebase';
type Player={uid:string;name:string;avatar:string;bot?:boolean;ready:boolean};type Room={id:string;code:string;name:string;hostId:string;status:string;visibility:'public'|'private';maxPlayers:number;players:Player[]};
const makeCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
export default function Room(){const{profile}=useAuth();const[params]=useSearchParams();const[room,setRoom]=useState<Room|null>(null);const[publicRooms,setPublicRooms]=useState<Room[]>([]);const[input,setInput]=useState('');const[error,setError]=useState('');const[visibility,setVisibility]=useState<'public'|'private'>('public');
 const create=async()=>{if(!profile||!db){setError('Firebase chưa được cấu hình.');return;}const data={code:makeCode(),name:`Phòng của ${profile.displayName}`,hostId:profile.uid,status:'waiting',visibility,maxPlayers:8,players:[{uid:profile.uid,name:profile.displayName,avatar:profile.photoURL,ready:true}],createdAt:serverTimestamp()};const ref=await addDoc(collection(db,'rooms'),data);setRoom({id:ref.id,...data} as Room)};
 useEffect(()=>{if(params.get('create')&&!room&&profile&&db)void create()},[profile]);
 useEffect(()=>{if(!db)return;const q=query(collection(db,'rooms'),where('visibility','==','public'),where('status','==','waiting'),limit(20));return onSnapshot(q,s=>setPublicRooms(s.docs.map(d=>({id:d.id,...d.data()} as Room)).filter(r=>r.players.length<r.maxPlayers)))},[]);
 useEffect(()=>{if(!db||!room)return;return onSnapshot(doc(db,'rooms',room.id),s=>{if(s.exists())setRoom({id:s.id,...s.data()} as Room);else setRoom(null)})},[room?.id]);
 const joinRoom=async(target:Room)=>{if(!profile||!db)return;if(target.players.some(p=>p.uid===profile.uid)){setRoom(target);return;}if(target.status!=='waiting'||target.players.length>=target.maxPlayers){setError('Phòng đã bắt đầu hoặc đã đủ người.');return;}const next=[...target.players,{uid:profile.uid,name:profile.displayName,avatar:profile.photoURL,ready:false}];await updateDoc(doc(db,'rooms',target.id),{players:next});setRoom({...target,players:next})};
 const joinByCode=async()=>{if(!db||!input.trim())return;const q=query(collection(db,'rooms'),where('code','==',input.trim().toUpperCase()),limit(1));const snap=await getDocs(q);if(snap.empty){setError('Không tìm thấy phòng.');return;}await joinRoom({id:snap.docs[0].id,...snap.docs[0].data()} as Room)};
 const addBot=async()=>{if(!room||!db||profile?.uid!==room.hostId||room.players.length>=room.maxPlayers)return;const next=[...room.players,{uid:`bot-${crypto.randomUUID()}`,name:`AI Thợ Mỏ ${room.players.filter(p=>p.bot).length+1}`,avatar:'',bot:true,ready:true}];await updateDoc(doc(db,'rooms',room.id),{players:next})};
 if(!profile)return <section className="center-page"><div className="auth-card"><LockKeyhole/><h1>CẦN ĐĂNG NHẬP</h1></div></section>;
 if(!room)return <section className="room-entry"><div className="room-entry-copy"><span>ONLINE FIRESTORE</span><h1>TẠO HOẶC<br/>THAM GIA PHÒNG</h1><p>Phòng hỗ trợ 6–8 người. Vai trò được giữ bí mật khi bắt đầu.</p></div><div className="room-browser"><div className="join-card"><Radio/><h2>NHẬP MÃ PHÒNG</h2><input value={input} onChange={e=>setInput(e.target.value.toUpperCase())} maxLength={6} placeholder="VD: A7K92X"/><button onClick={joinByCode} className="btn btn-primary">VÀO PHÒNG</button><div className="or"><span/>HOẶC<span/></div><label>Loại phòng<select value={visibility} onChange={e=>setVisibility(e.target.value as any)}><option value="public">Công khai</option><option value="private">Riêng tư</option></select></label><button onClick={create} className="btn btn-ghost"><Plus/> TẠO PHÒNG MỚI</button>{error&&<p className="error">{error}</p>}</div><div className="public-room-list panel"><header><Globe2/> PHÒNG CÔNG KHAI ĐANG CHỜ</header>{publicRooms.length===0?<p className="empty-public">Chưa có phòng công khai nào.</p>:publicRooms.map(r=><button key={r.id} onClick={()=>joinRoom(r)}><div><b>{r.name}</b><small>#{r.code}</small></div><span>{r.players.length}/{r.maxPlayers}</span></button>)}</div></div></section>;
 const isHost=profile.uid===room.hostId;return <section className="lobby-page"><div className="lobby-head"><div><span>PHÒNG CHỜ · {room.visibility==='public'?'CÔNG KHAI':'RIÊNG TƯ'}</span><h1>#{room.code}</h1></div><button className="btn btn-ghost btn-small" onClick={()=>navigator.clipboard.writeText(room.code)}><Copy/> Sao chép mã</button></div><div className="lobby-grid"><div className="panel lobby-players"><header><Users/> ĐỘI HÌNH ({room.players.length}/{room.maxPlayers})</header>{Array.from({length:room.maxPlayers},(_,i)=>{const p=room.players[i];return p?<div className="lobby-player" key={p.uid}><span>{p.bot?<Bot/>:p.uid===room.hostId?<Pickaxe/>:<UserRound/>}</span><div><b>{p.name}</b><small>{p.uid===room.hostId?'CHỦ PHÒNG':p.bot?'AI':'NGƯỜI CHƠI'}</small></div><em>{p.ready?'SẴN SÀNG':'ĐANG CHỜ'}</em></div>:<div className="empty-slot" key={i}>VỊ TRÍ TRỐNG</div>})}{isHost&&<button onClick={addBot} disabled={room.players.length>=room.maxPlayers} className="btn btn-ghost"><Bot/> THÊM AI</button>}</div><div className="panel room-settings"><header><DoorOpen/> THIẾT LẬP TRẬN</header><div className="setting-row"><span>Bàn chơi</span><b>12×5</b></div><div className="setting-row"><span>Người chơi</span><b>6–8</b></div><div className="setting-row"><span>Vai trò</span><b>BÍ MẬT</b></div>{isHost?<Link to={`/game?mode=room&room=${room.id}&players=${room.players.length}`} className={`btn btn-primary btn-wide ${room.players.length<6?'disabled-link':''}`}>BẮT ĐẦU TRẬN</Link>:<div className="waiting-host"><Radio/> Đang chờ chủ phòng bắt đầu...</div>}{room.players.length<6&&<small>Cần thêm {6-room.players.length} người hoặc AI.</small>}</div></div></section>}
