import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import { browserLocalPersistence, browserSessionPersistence, getRedirectResult, onAuthStateChanged, setPersistence, signInWithPopup, signInWithRedirect, signOut, User } from 'firebase/auth';
import { doc, getDoc, increment, runTransaction, serverTimestamp, setDoc, updateDoc } from 'firebase/firestore';
import { auth, db, firebaseReady, googleProvider } from '../lib/firebase';
import { legacyRankPoints, MatchReward, rankDelta, rankFromPoints } from '../lib/progression';
import { MISSIONS, missionProgress, todayKey } from '../lib/missions';
import { SHOP_ITEMS } from '../lib/shop';

export type Equipped={frame?:string;nameColor?:string;nameplate?:string;title?:string;badge?:string;boardSkin?:string;pieceSkin?:string};
export type Profile={uid:string;displayName:string;email:string;photoURL:string;rank:string;rankPoints:number;exp:number;coins:number;wins:number;losses:number;gamesPlayed:number;ownedItems:string[];equipped:Equipped;missionDate:string;onlineSecondsToday:number;dailyGames:number;dailyWins:number;dailyChats:number;claimedDailyMissions:string[];claimedAchievements:string[]};
type AuthValue={user:User|null;profile:Profile|null;loading:boolean;firebaseReady:boolean;login:()=>Promise<void>;logout:()=>Promise<void>;completeMatch:(won:boolean,matchId:string,reward:MatchReward,details?:{role?:string;turns?:number;durationSeconds?:number;opponents?:string[]})=>Promise<boolean>;buyItem:(itemId:string)=>Promise<void>;equipItem:(itemId:string)=>Promise<void>;claimMission:(missionId:string)=>Promise<void>;recordChatMessage:()=>Promise<void>};
const C=createContext<AuthValue|null>(null);
const baseProfile=(u:User):Profile=>({uid:u.uid,displayName:u.displayName||'Người chơi',email:u.email||'',photoURL:u.photoURL||'',rank:'Bạc',rankPoints:1000,exp:0,coins:500,wins:0,losses:0,gamesPlayed:0,ownedItems:[],equipped:{},missionDate:todayKey(),onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[],claimedAchievements:[]});
const safeInt=(value:unknown,min:number,max:number,fallback=0)=>Number.isFinite(Number(value))?Math.min(max,Math.max(min,Math.floor(Number(value)))):fallback;
const normalize=(base:Profile,data:Partial<Profile>|undefined):Profile=>{const wins=safeInt(data?.wins,0,1_000_000),losses=safeInt(data?.losses,0,1_000_000),rankPoints=safeInt(data?.rankPoints,0,10000,legacyRankPoints(wins,losses));return{...base,...data,uid:base.uid,email:base.email,displayName:String(data?.displayName||base.displayName).slice(0,60),photoURL:String(data?.photoURL||base.photoURL).slice(0,500),rankPoints,rank:rankFromPoints(rankPoints).name,exp:safeInt(data?.exp,0,10_000_000),coins:safeInt(data?.coins,0,1_000_000,500),wins,losses,gamesPlayed:safeInt(data?.gamesPlayed,0,2_000_000),onlineSecondsToday:safeInt(data?.onlineSecondsToday,0,86400),dailyGames:safeInt(data?.dailyGames,0,1000),dailyWins:safeInt(data?.dailyWins,0,1000),dailyChats:safeInt(data?.dailyChats,0,500),ownedItems:Array.isArray(data?.ownedItems)?data.ownedItems.filter(x=>typeof x==='string').slice(0,200):[],equipped:data?.equipped&&typeof data.equipped==='object'?data.equipped:{},claimedDailyMissions:Array.isArray(data?.claimedDailyMissions)?data.claimedDailyMissions.filter(x=>typeof x==='string').slice(0,100):[],claimedAchievements:Array.isArray(data?.claimedAchievements)?data.claimedAchievements.filter(x=>typeof x==='string').slice(0,500):[]}};
export function AuthProvider({children}:{children:ReactNode}){
 const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{if(!auth||!db){setLoading(false);return undefined;}const a=auth,d=db;let active=true;const prepareAuth=async()=>{try{await setPersistence(a,browserLocalPersistence)}catch{try{await setPersistence(a,browserSessionPersistence)}catch{/* Auth vẫn có thể chạy với persistence mặc định. */}}try{await getRedirectResult(a)}catch(error){console.error('Firebase redirect result error:',error)}};void prepareAuth();const unsubscribe=onAuthStateChanged(a,async u=>{if(!active)return;setUser(u);if(!u){setProfile(null);setLoading(false);return;}const ref=doc(d,'users',u.uid),snap=await getDoc(ref),base=baseProfile(u);if(!snap.exists())await setDoc(ref,{...base,createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()});else await setDoc(ref,{displayName:base.displayName,email:base.email,photoURL:base.photoURL,lastLoginAt:serverTimestamp()},{merge:true});const next=normalize(base,snap.exists()?snap.data():base);if(next.missionDate!==todayKey()){next.missionDate=todayKey();next.onlineSecondsToday=0;next.dailyGames=0;next.dailyWins=0;next.dailyChats=0;next.claimedDailyMissions=[];await setDoc(ref,{missionDate:next.missionDate,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]},{merge:true})}setProfile(next);setLoading(false);});return ()=>{active=false;unsubscribe()};},[]);
 useEffect(()=>{if(!profile||!user||!db)return;let last=Date.now();const tick=async()=>{const now=Date.now();if(document.visibilityState!=='visible'){last=now;return}const seconds=Math.min(35,Math.max(0,Math.floor((now-last)/1000)));last=now;if(seconds<1)return;const date=todayKey();const ref=doc(db!,'users',user.uid);if(profile.missionDate!==date){await setDoc(ref,{missionDate:date,onlineSecondsToday:seconds,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[],lastHeartbeatAt:serverTimestamp()},{merge:true});setProfile(p=>p?{...p,missionDate:date,onlineSecondsToday:seconds,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]}:p)}else{await updateDoc(ref,{onlineSecondsToday:increment(seconds),lastHeartbeatAt:serverTimestamp()});setProfile(p=>p?{...p,onlineSecondsToday:p.onlineSecondsToday+seconds}:p)}};const timer=window.setInterval(()=>void tick(),30000);const onVisibility=()=>{last=Date.now()};document.addEventListener('visibilitychange',onVisibility);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',onVisibility)}},[user?.uid,profile?.missionDate]);
 const login=async()=>{
  if(!auth)throw new Error('Firebase chưa được cấu hình.');
  try{await setPersistence(auth,browserLocalPersistence)}catch{try{await setPersistence(auth,browserSessionPersistence)}catch{/* dùng persistence mặc định */}}
  try{
   // Popup được gọi trực tiếp từ thao tác nhấn nút nên hoạt động ổn định hơn redirect
   // trên Safari/iOS và Chrome mobile khi app không host cùng authDomain.
   await signInWithPopup(auth,googleProvider);
  }catch(e:any){
   const code=String(e?.code||'');
   if(code==='auth/popup-closed-by-user'||code==='auth/cancelled-popup-request')throw new Error('Bạn đã đóng cửa sổ đăng nhập Google.');
   if(code==='auth/unauthorized-domain')throw new Error(`Tên miền ${window.location.hostname} chưa được thêm vào Firebase Authentication > Authorized domains.`);
   if(code==='auth/popup-blocked'||code==='auth/operation-not-supported-in-this-environment'){
    await signInWithRedirect(auth,googleProvider);
    return;
   }
   if(code==='auth/web-storage-unsupported')throw new Error('Trình duyệt đang chặn bộ nhớ đăng nhập. Hãy tắt chế độ duyệt riêng tư hoặc cho phép cookie cho trang này.');
   if(code==='auth/network-request-failed')throw new Error('Không kết nối được Firebase. Hãy kiểm tra mạng rồi thử lại.');
   throw e;
  }
 };
 const logout=async()=>{if(auth)await signOut(auth)};
 const completeMatch=async(won:boolean,matchId:string,reward:MatchReward,details?:{role?:string;turns?:number;durationSeconds?:number;opponents?:string[]})=>{if(!profile||!db||!user)return false;const safeReward={exp:safeInt(reward.exp,0,500),coins:safeInt(reward.coins,0,500)};const userRef=doc(db,'users',user.uid),claimRef=doc(db,'users',user.uid,'completedMatches',matchId),historyRef=doc(db,'users',user.uid,'matchHistory',matchId);let next:Profile|undefined;const accepted=await runTransaction(db,async tx=>{if((await tx.get(claimRef)).exists())return false;const snap=await tx.get(userRef);let current=normalize(profile,snap.data()||{});const date=todayKey();if(current.missionDate!==date)current={...current,missionDate:date,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]};const rankPoints=Math.max(0,current.rankPoints+rankDelta(won,current.rankPoints));next={...current,exp:current.exp+safeReward.exp,coins:current.coins+safeReward.coins,wins:current.wins+(won?1:0),losses:current.losses+(won?0:1),gamesPlayed:current.gamesPlayed+1,dailyGames:current.dailyGames+1,dailyWins:current.dailyWins+(won?1:0),rankPoints,rank:rankFromPoints(rankPoints).name};tx.set(claimRef,{won,reward:safeReward,completedAt:serverTimestamp()});tx.set(historyRef,{matchId,won,role:String(details?.role||'unknown').slice(0,30),turns:safeInt(details?.turns,0,10000),durationSeconds:safeInt(details?.durationSeconds,0,86400),opponents:Array.isArray(details?.opponents)?details!.opponents!.filter(x=>typeof x==='string').slice(0,10).map(x=>x.slice(0,60)):[],reward:safeReward,rankDelta:rankPoints-current.rankPoints,completedAt:serverTimestamp()});tx.set(userRef,next,{merge:true});return true;});if(accepted&&next)setProfile(next);return accepted;};
 const recordChatMessage=async()=>{if(!profile||!db||!user)return;const date=todayKey(),reset=profile.missionDate!==date;const patch=reset?{missionDate:date,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:1,claimedDailyMissions:[]}:{dailyChats:increment(1)};await setDoc(doc(db,'users',user.uid),patch,{merge:true});setProfile(p=>p?reset?{...p,missionDate:date,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:1,claimedDailyMissions:[]}:{...p,dailyChats:p.dailyChats+1}:p)};
 const claimMission=async(missionId:string)=>{if(!profile||!db||!user)return;const mission=MISSIONS.find(m=>m.id===missionId);if(!mission)throw new Error('Nhiệm vụ không tồn tại.');let next:Profile|undefined;await runTransaction(db,async tx=>{const ref=doc(db!,'users',user.uid),snap=await tx.get(ref);let current=normalize(profile,snap.data()||{});const date=todayKey();if(current.missionDate!==date)current={...current,missionDate:date,onlineSecondsToday:0,dailyGames:0,dailyWins:0,dailyChats:0,claimedDailyMissions:[]};const claimed=mission.kind==='daily'?current.claimedDailyMissions:current.claimedAchievements;if(claimed.includes(mission.id))return;if(missionProgress(mission,current)<mission.target)throw new Error('Nhiệm vụ chưa hoàn thành.');next={...current,coins:current.coins+mission.rewardCoins,exp:current.exp+mission.rewardExp,claimedDailyMissions:mission.kind==='daily'?[...current.claimedDailyMissions,mission.id]:current.claimedDailyMissions,claimedAchievements:mission.kind==='achievement'?[...current.claimedAchievements,mission.id]:current.claimedAchievements};tx.set(ref,next,{merge:true})});if(next)setProfile(next)};
 const buyItem=async(itemId:string)=>{if(!profile||!db||!user)return;const item=SHOP_ITEMS.find(x=>x.id===itemId);if(!item)throw new Error('Vật phẩm không tồn tại.');let next:Profile|undefined;await runTransaction(db,async tx=>{const ref=doc(db!,'users',user.uid),snap=await tx.get(ref),current=normalize(profile,snap.data()||{});if(current.ownedItems.includes(itemId))return;if(current.coins<item.price)throw new Error('Bạn không đủ vàng.');next={...current,coins:current.coins-item.price,ownedItems:[...current.ownedItems,itemId]};tx.set(ref,next,{merge:true});});if(next)setProfile(next);};
 const equipItem=async(itemId:string)=>{if(!profile||!db||!user)return;const item=SHOP_ITEMS.find(x=>x.id===itemId);if(!item||!profile.ownedItems.includes(itemId))throw new Error('Bạn chưa sở hữu vật phẩm này.');const equipped={...profile.equipped,[item.category]:itemId},next={...profile,equipped};setProfile(next);await setDoc(doc(db,'users',user.uid),{equipped},{merge:true});};
 const value=useMemo(()=>({user,profile,loading,firebaseReady,login,logout,completeMatch,buyItem,equipItem,claimMission,recordChatMessage}),[user,profile,loading]);return <C.Provider value={value}>{children}</C.Provider>;
}
export const useAuth=()=>{const v=useContext(C);if(!v)throw new Error('AuthProvider missing');return v};
