import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';
import { browserLocalPersistence, getRedirectResult, onAuthStateChanged, setPersistence, signInWithPopup, signInWithRedirect, signOut, User } from 'firebase/auth';
import { doc, getDoc, runTransaction, serverTimestamp, setDoc } from 'firebase/firestore';
import { auth, db, firebaseReady, googleProvider } from '../lib/firebase';
import { MatchReward, rankFromExp } from '../lib/progression';
import { SHOP_ITEMS } from '../lib/shop';

export type Equipped={frame?:string;nameColor?:string;nameplate?:string;title?:string;badge?:string};
export type Profile={uid:string;displayName:string;email:string;photoURL:string;rank:string;exp:number;coins:number;wins:number;losses:number;gamesPlayed:number;ownedItems:string[];equipped:Equipped};
type AuthValue={user:User|null;profile:Profile|null;loading:boolean;firebaseReady:boolean;login:()=>Promise<void>;logout:()=>Promise<void>;completeMatch:(won:boolean,matchId:string,reward:MatchReward)=>Promise<boolean>;buyItem:(itemId:string)=>Promise<void>;equipItem:(itemId:string)=>Promise<void>};
const C=createContext<AuthValue|null>(null);
const baseProfile=(u:User):Profile=>({uid:u.uid,displayName:u.displayName||'Người chơi',email:u.email||'',photoURL:u.photoURL||'',rank:'Đồng',exp:0,coins:500,wins:0,losses:0,gamesPlayed:0,ownedItems:[],equipped:{}});
export function AuthProvider({children}:{children:ReactNode}){
 const[user,setUser]=useState<User|null>(null);const[profile,setProfile]=useState<Profile|null>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{if(!auth||!db){setLoading(false);return;}const a=auth,d=db;void setPersistence(a,browserLocalPersistence);void getRedirectResult(a).catch(()=>undefined);return onAuthStateChanged(a,async u=>{setUser(u);if(!u){setProfile(null);setLoading(false);return;}const ref=doc(d,'users',u.uid),snap=await getDoc(ref),base=baseProfile(u);if(!snap.exists())await setDoc(ref,{...base,createdAt:serverTimestamp(),lastLoginAt:serverTimestamp()});else await setDoc(ref,{displayName:base.displayName,email:base.email,photoURL:base.photoURL,lastLoginAt:serverTimestamp()},{merge:true});setProfile(snap.exists()?({...base,...snap.data(),ownedItems:snap.data().ownedItems||[],equipped:snap.data().equipped||{}} as Profile):base);setLoading(false);});},[]);
 const login=async()=>{if(!auth)throw new Error('Firebase chưa được cấu hình.');const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);if(mobile)await signInWithRedirect(auth,googleProvider);else try{await signInWithPopup(auth,googleProvider)}catch(e:any){if(['auth/popup-blocked','auth/cancelled-popup-request','auth/operation-not-supported-in-this-environment'].includes(e?.code))await signInWithRedirect(auth,googleProvider);else throw e;}};
 const logout=async()=>{if(auth)await signOut(auth)};
 const completeMatch=async(won:boolean,matchId:string,reward:MatchReward)=>{if(!profile||!db||!user)return false;const safeReward={exp:Math.max(0,Math.floor(reward.exp)),coins:Math.max(0,Math.floor(reward.coins))};const userRef=doc(db,'users',user.uid),claimRef=doc(db,'users',user.uid,'completedMatches',matchId);let next:Profile|undefined;const accepted=await runTransaction(db,async tx=>{if((await tx.get(claimRef)).exists())return false;const snap=await tx.get(userRef);const current={...profile,...(snap.data()||{})} as Profile;next={...current,exp:current.exp+safeReward.exp,coins:current.coins+safeReward.coins,wins:current.wins+(won?1:0),losses:current.losses+(won?0:1),gamesPlayed:current.gamesPlayed+1,rank:rankFromExp(current.exp+safeReward.exp)};tx.set(claimRef,{won,reward:safeReward,completedAt:serverTimestamp()});tx.set(userRef,next,{merge:true});return true;});if(accepted&&next)setProfile(next);return accepted;};
 const buyItem=async(itemId:string)=>{if(!profile||!db||!user)return;const item=SHOP_ITEMS.find(x=>x.id===itemId);if(!item)throw new Error('Vật phẩm không tồn tại.');let next:Profile|undefined;await runTransaction(db,async tx=>{const ref=doc(db!,'users',user.uid),snap=await tx.get(ref),current={...profile,...snap.data(),ownedItems:(snap.data()?.ownedItems||profile.ownedItems||[])} as Profile;if(current.ownedItems.includes(itemId))return;if(current.coins<item.price)throw new Error('Bạn không đủ vàng.');next={...current,coins:current.coins-item.price,ownedItems:[...current.ownedItems,itemId]};tx.set(ref,next,{merge:true});});if(next)setProfile(next);};
 const equipItem=async(itemId:string)=>{if(!profile||!db||!user)return;const item=SHOP_ITEMS.find(x=>x.id===itemId);if(!item||!profile.ownedItems.includes(itemId))throw new Error('Bạn chưa sở hữu vật phẩm này.');const equipped={...profile.equipped,[item.category]:itemId},next={...profile,equipped};setProfile(next);await setDoc(doc(db,'users',user.uid),{equipped},{merge:true});};
 const value=useMemo(()=>({user,profile,loading,firebaseReady,login,logout,completeMatch,buyItem,equipItem}),[user,profile,loading]);return <C.Provider value={value}>{children}</C.Provider>;
}
export const useAuth=()=>{const v=useContext(C);if(!v)throw new Error('AuthProvider missing');return v};
